Repository snyk/driftctl, pull requests merged in 2020-12, with the labels that each got.

#10 Add policy doc for remote s3 state
  doc/cmd/scan/iac_source.md
Labels: kind/documentation

#23 Add stale app
  .github/stale.yml
Labels: kind/maintenance

#4 add a docker for drifctl
  .dockerignore
  Dockerfile
  README.md
  scripts/build.sh
Labels: kind/maintenance

#24 Add release drafter
  .github/release-drafter.yml
Labels: kind/maintenance

#27 Updated documentation usage for aws creds
  README.md
Labels: kind/documentation

#35 Add doc issue template
  .github/ISSUE_TEMPLATE/documentation.md
Labels: kind/maintenance

#34 Add env to disable version check
  doc/README.md
  pkg/cmd/driftctl.go
  pkg/cmd/driftctl_test.go
Labels: kind/enhancement

#43 updated doc following user feedback
  README.md
Labels: kind/documentation

#52 Add documentation about AWS authentication
  README.md
  doc/cmd/scan/supported_resources/aws.md
Labels: kind/documentation

#49 Add missing aws permissions for aws_vpc and aws_default_vpc resources
  doc/cmd/scan/supported_resources/aws.md
Labels: kind/documentation
