Repository snyk/driftctl, pull requests merged in 2021-02, with the labels that each got.

#178 skip warnings on commented out and empty lines
  pkg/filter/driftignore.go
  pkg/filter/testdata/drift_ignore_valid/.driftignore
Labels: kind/enhancement

#180 Fix lint sometimes fail in CI
  Makefile
Labels: kind/maintenance

#186 Update CloudFormation launch stack docs
  doc/cmd/scan/supported_resources/aws.md
Labels: kind/documentation

#181 Add contributions country flags
  README.md
Labels: kind/documentation

#182 add LIMITATIONS.md
  doc/LIMITATIONS.md
  doc/README.md
Labels: kind/documentation

#177 Embed the environment variables before PreExec in ACC test
  test/acceptance/testing.go
Labels: kind/bug

#179 Add CI config to schedule acceptance tests
  .circleci/config.yml
  pkg/resource/aws/testdata/acc/aws_security_group/.terraform.lock.hcl
Labels: kind/maintenance

#190 Add build checksums
  scripts/build.sh
Labels: kind/maintenance

#192 Make sentry attach stack for every report
  pkg/cmd/driftctl.go
Labels: kind/maintenance

#203 Fix unexpected deleted resources in acceptance tests
  pkg/resource/aws/aws_instance_test.go
  test/acceptance/testing.go
Labels: kind/bug

#208 Remove reference used in loops
  .golangci.yml
  pkg/remote/aws/ec2_eip_association_supplier.go
  pkg/remote/aws/iam_role_policy_supplier.go
  pkg/remote/aws/vpc_security_group_rule_supplier.go
  pkg/resource/aws/deserializer/db_instance_deserializer.go
  pkg/resource/aws/deserializer/db_subnet_group_deserializer.go
  pkg/resource/aws/deserializer/default_route_table_deserializer.go
  pkg/resource/aws/deserializer/default_security_group_deserializer.go
  pkg/resource/aws/deserializer/default_subnet_deserializer.go
  pkg/resource/aws/deserializer/default_vpc_deserializer.go
  pkg/resource/aws/deserializer/internet_gateway_deserializer.go
  pkg/resource/aws/deserializer/nat_gateway_deserializer.go
  pkg/resource/aws/deserializer/route53_record_deserializer.go
  pkg/resource/aws/deserializer/route53_zone_deserializer.go
  pkg/resource/aws/deserializer/route_deserializer.go
  pkg/resource/aws/deserializer/route_table_association_deserializer.go
  pkg/resource/aws/deserializer/route_table_deserializer.go
  pkg/resource/aws/deserializer/sqs_queue_deserializer.go
  pkg/resource/aws/deserializer/sqs_queue_policy_deserializer.go
  pkg/resource/aws/deserializer/subnet_deserializer.go
  pkg/resource/aws/deserializer/vpc_deserializer.go
Labels: kind/bug

#193 Handle invalid route crash in middlewares
  mocks/AlerterInterface.go
  pkg/alerter/alerter.go
  pkg/driftctl.go
  pkg/middlewares/aws_route_table_expander.go
  pkg/middlewares/aws_route_table_expander_test.go
  pkg/remote/aws/route_supplier.go
  pkg/resource/aws/aws_route_ext.go
Labels: kind/bug

#214 Add random string in s3 acc test bucket name
  pkg/resource/aws/aws_s3_bucket_test.go
  pkg/resource/aws/testdata/acc/aws_s3_bucket/s3.tf
Labels: kind/maintenance

#209 Replace manual terraform execution with hashicorp/terraform-exec
  go.mod
  go.sum
  test/acceptance/testing.go
  test/acceptance/testing_test.go
Labels: kind/maintenance

#205 Sign releases using PGP
  .circleci/config.yml
  README.md
Labels: kind/maintenance

#189 More readable aws resources scan output
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/testdata/output_stringer_resources.txt
  pkg/resource/aws/aws_route53_record_ext.go
  pkg/resource/aws/aws_route53_record_ext_test.go
  pkg/resource/aws/aws_route53_zone_ext.go
  pkg/resource/aws/aws_route53_zone_test.go
Labels: kind/enhancement

#227 Fix policy diff displayed inline
  pkg/resource/aws/aws_sns_topic.go
  pkg/resource/aws/aws_sns_topic_policy.go
  pkg/resource/aws/aws_sqs_queue_policy.go
Labels: kind/bug

#228 Fix false positive drifts on aws_sns_topic
  pkg/iac/terraform/state/test/sns_topic/result.golden.json
  pkg/resource/aws/aws_sns_topic_ext.go
Labels: kind/bug

#230 updates to gpg doc to make it work out of the box
  README.md
Labels: kind/documentation

#222 Split lint from test
  .circleci/config.yml
  Makefile
Labels: kind/maintenance

#225 Make provider install and download independent from aws
  pkg/remote/aws/terraform_provider.go
  pkg/terraform/provider_config.go
  pkg/terraform/provider_config_test.go
  pkg/terraform/provider_downloader.go
  pkg/terraform/provider_downloader_test.go
  pkg/terraform/provider_installer.go
  pkg/terraform/provider_installer_test.go
Labels: kind/maintenance

#231 fix policies in topic subscription not beeing tag as jsonstring
  pkg/resource/aws/aws_sns_topic_subscription.go
Labels: kind/bug

#229 Improve aws_iam_access_key output
  pkg/resource/aws/aws_iam_access_key_ext.go
  pkg/resource/aws/aws_iam_access_key_test.go
Labels: kind/enhancement

#233 docs: add more examples to filter.md for prefix/suffix
  doc/cmd/scan/filter.md
Labels: kind/documentation

#236 Fix invalid AWS policy
  doc/cmd/scan/supported_resources/aws.md
Labels: kind/documentation

#238 add Terraform known limitations
  doc/LIMITATIONS.md
Labels: kind/documentation

#237 add polling for sns acc tests
  pkg/resource/aws/aws_sns_topic_policy_test.go
  pkg/resource/aws/aws_sns_topic_subscription_test.go
  pkg/resource/aws/aws_sns_topic_test.go
Labels: kind/maintenance

#239 Better error handling
  main.go
  pkg/cmd/driftctl.go
  pkg/cmd/driftctl_test.go
  pkg/cmd/errors/errors.go
  pkg/cmd/scan.go
  pkg/cmd/scan_test.go
  pkg/driftctl.go
  pkg/iac/supplier/supplier.go
  pkg/iac/terraform/state/backend/backend.go
  pkg/iac/terraform/state/backend/s3_reader.go
  pkg/parallel/parallel_runner.go
  pkg/remote/remote.go
  pkg/resource/aws/aws_route_ext.go
  pkg/scanner.go
  pkg/terraform/provider_downloader.go
  pkg/terraform/provider_installer.go
  sentry/sentry.go
  sentry/sentry_test.go
Labels: kind/maintenance

#241 Better log handler for terraform providers
  logger/config.go
  logger/logger.go
  logger/plugin_logger.go
  main.go
  pkg/terraform/plugin_client.go
  test/acceptance/testing.go
Labels: kind/maintenance

#260 Allow to run acceptance tests in parallel
  .circleci/config.yml
  Makefile
Labels: kind/maintenance

#263 Improve acceptance test notifications
  .circleci/config.yml
Labels: kind/maintenance

#258 Add support for github_repository
  .mockery.yaml
  doc/cmd/scan/supported_resources/README.md
  doc/cmd/scan/supported_resources/github.md
  go.mod
  go.sum
  mocks/GithubGraphQLClient.go
  pkg/cmd/driftctl_test.go
  pkg/cmd/scan_test.go
  pkg/iac/deserializers.go
  pkg/iac/terraform/state/terraform_state_reader.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/github_repository/result.golden.json
  pkg/iac/terraform/state/test/github_repository/schema.golden.json
  pkg/iac/terraform/state/test/github_repository/terraform.tfstate
  pkg/remote/aws/provider.go
  pkg/remote/github/github_repository_supplier.go
  pkg/remote/github/github_repository_supplier_test.go
  pkg/remote/github/init.go
  pkg/remote/github/init_test.go
  pkg/remote/github/mock_GithubRepository_test.go
  pkg/remote/github/provider.go
  pkg/remote/github/repository.go
  pkg/remote/github/repository_test.go
  pkg/remote/github/test/github_repository_empty/results.golden.json
  pkg/remote/github/test/github_repository_empty/schema.golden.json
  pkg/remote/github/test/github_repository_multiple/github_repository-driftctl-demos.res.golden.json
  pkg/remote/github/test/github_repository_multiple/github_repository-driftctl.res.golden.json
  pkg/remote/github/test/github_repository_multiple/results.golden.json
  pkg/remote/github/test/github_repository_multiple/schema.golden.json
  pkg/remote/remote.go
  pkg/remote/terraform/provider.go
  pkg/resource/github/deserializer/github_repository_deserializer.go
  pkg/resource/github/github_repository.go
  pkg/resource/github/github_repository_ext.go
  pkg/resource/github/github_repository_test.go
  pkg/resource/github/testdata/acc/github_repository/.terraform.lock.hcl
  pkg/resource/github/testdata/acc/github_repository/repository.tf
  pkg/resource/github/testdata/acc/github_repository/terraform.tf
  pkg/terraform/provider_config.go
  pkg/terraform/provider_config_test.go
  pkg/terraform/providers.go
Labels: kind/enhancement

#264 Add documentation on log level
  doc/README.md
Labels: kind/documentation

#267 Point to the policy for driftctl when an access denied is encountered
  pkg/alerter/alert.go
  pkg/alerter/alerter.go
  pkg/alerter/alerter_test.go
  pkg/analyser/analysis.go
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/console_test.go
  pkg/cmd/scan/output/json_test.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output_access_denied_alert.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert.txt
  pkg/middlewares/aws_route_table_expander.go
  pkg/middlewares/aws_route_table_expander_test.go
  pkg/remote/resource_enumeration_error_handler.go
  pkg/remote/resource_enumeration_error_handler_test.go
Labels: kind/enhancement

#268 Update to go 1.16
  .circleci/config.yml
  .go-version
  Dockerfile
  go.mod
  go.sum
  pkg/terraform/provider_config.go
  pkg/terraform/provider_config_test.go
  scripts/build.sh
Labels: kind/enhancement

#275 Fix bucket location returns EU for buckets in eu-west-1
  pkg/remote/aws/s3_bucket_supplier.go
Labels: kind/bug

#266 Remove custom mock and add repository for S3
  pkg/remote/aws/client/mock_AwsClientFactoryInterface.go
  pkg/remote/aws/client/s3_client_factory.go
  pkg/remote/aws/init.go
  pkg/remote/aws/repository/mock_S3Repository.go
  pkg/remote/aws/repository/s3_repository.go
  pkg/remote/aws/repository/s3_repository_test.go
  pkg/remote/aws/s3_bucket_analytic_supplier.go
  pkg/remote/aws/s3_bucket_analytic_supplier_test.go
  pkg/remote/aws/s3_bucket_inventory_supplier.go
  pkg/remote/aws/s3_bucket_inventory_supplier_test.go
  pkg/remote/aws/s3_bucket_metric_supplier_test.go
  pkg/remote/aws/s3_bucket_metrics_supplier.go
  pkg/remote/aws/s3_bucket_notification_supplier.go
  pkg/remote/aws/s3_bucket_notification_supplier_test.go
  pkg/remote/aws/s3_bucket_policy_supplier.go
  pkg/remote/aws/s3_bucket_policy_supplier_test.go
  pkg/remote/aws/s3_bucket_supplier.go
  pkg/remote/aws/s3_bucket_supplier_test.go
  test/mocks/MockAwsClientFactory.go
  test/mocks/MockAwsS3Client.go
Labels: kind/maintenance

#278 Add doc to filter on archived repos
  doc/cmd/scan/filter.md
Labels: kind/documentation

#287 New Homebrew Secrets
  .github/workflows/homebrew.yml
Labels: kind/maintenance

#290 Allow prefix usage in iac source for s3
  Makefile
  doc/cmd/scan/iac_source.md
  pkg/iac/supplier/supplier_test.go
  pkg/iac/terraform/state/backend/backend.go
  pkg/iac/terraform/state/backend/file_reader.go
  pkg/iac/terraform/state/backend/s3_reader.go
  pkg/iac/terraform/state/enumerator/s3.go
  pkg/iac/terraform/state/enumerator/s3_test.go
  pkg/iac/terraform/state/enumerator/state_enumerator.go
  pkg/iac/terraform/state/terraform_state_reader.go
  pkg/iac/terraform/state/terraform_state_reader_acc_test.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/testdata/acc/multiples_states/route53/.terraform.lock.hcl
  pkg/iac/terraform/state/testdata/acc/multiples_states/route53/terraform.tf
  pkg/iac/terraform/state/testdata/acc/multiples_states/s3/.terraform.lock.hcl
  pkg/iac/terraform/state/testdata/acc/multiples_states/s3/terraform.tf
  pkg/resource/aws/aws_cloudfront_distribution_test.go
  pkg/resource/aws/aws_dynamodb_table_test.go
  pkg/resource/aws/aws_instance_test.go
  pkg/resource/aws/aws_internet_gateway_test.go
  pkg/resource/aws/aws_nat_gateway_test.go
  pkg/resource/aws/aws_route53_health_check_test.go
  pkg/resource/aws/aws_route53_record_test.go
  pkg/resource/aws/aws_route_table_association_test.go
  pkg/resource/aws/aws_route_table_test.go
  pkg/resource/aws/aws_route_test.go
  pkg/resource/aws/aws_s3_bucket_test.go
  pkg/resource/aws/aws_security_group_test.go
  pkg/resource/aws/aws_sns_topic_policy_test.go
  pkg/resource/aws/aws_sns_topic_subscription_test.go
  pkg/resource/aws/aws_sns_topic_test.go
  pkg/resource/aws/aws_sqs_queue_policy_test.go
  pkg/resource/aws/aws_sqs_queue_test.go
  pkg/resource/aws/aws_subnet_test.go
  pkg/resource/github/github_repository_test.go
  test/acceptance/result.go
  test/acceptance/testing.go
Labels: kind/enhancement

#299 Update Cloudfront distribution normalization
  pkg/iac/terraform/state/test/cloudfront_distribution/result.golden.json
  pkg/iac/terraform/state/test/cloudfront_distribution/terraform.tfstate
  pkg/resource/aws/aws_cloudfront_distribution_ext.go
Labels: kind/bug

#295 refacto lambda supplier and test to use mock and repository
  go.sum
  pkg/remote/aws/lambda_function_supplier.go
  pkg/remote/aws/lambda_function_supplier_test.go
  pkg/remote/aws/repository/lambda_repository.go
  pkg/remote/aws/repository/lambda_repository_test.go
  pkg/remote/aws/repository/mock_LambdaClient.go
  pkg/remote/aws/repository/mock_LambdaRepository.go
  test/mocks/MockAwsLambdaClient.go
Labels: kind/maintenance

#297 refacto rds supplier and test to use mock and repository
  pkg/remote/aws/db_instance_supplier.go
  pkg/remote/aws/db_instance_supplier_test.go
  pkg/remote/aws/db_subnet_group_supplier.go
  pkg/remote/aws/db_subnet_group_supplier_test.go
  pkg/remote/aws/repository/mock_RDSClient.go
  pkg/remote/aws/repository/mock_RDSRepository.go
  pkg/remote/aws/repository/rds_repository.go
  pkg/remote/aws/repository/rds_repository_test.go
  test/mocks/MockAwsRDSClient.go
Labels: kind/maintenance

#293 Add github_team
  doc/cmd/scan/supported_resources/github.md
  pkg/iac/deserializers.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/github_team/result.golden.json
  pkg/iac/terraform/state/test/github_team/schema.golden.json
  pkg/iac/terraform/state/test/github_team/terraform.tf
  pkg/iac/terraform/state/test/github_team/terraform.tfstate
  pkg/remote/github/github_team_supplier.go
  pkg/remote/github/github_team_supplier_test.go
  pkg/remote/github/init.go
  pkg/remote/github/mock_GithubRepository.go
  pkg/remote/github/repository.go
  pkg/remote/github/repository_test.go
  pkg/remote/github/test/github_teams_empty/results.golden.json
  pkg/remote/github/test/github_teams_empty/schema.golden.json
  pkg/remote/github/test/github_teams_multiple/github_team-4556811.res.golden.json
  pkg/remote/github/test/github_teams_multiple/github_team-4556812.res.golden.json
  pkg/remote/github/test/github_teams_multiple/github_team-4556814.res.golden.json
  pkg/remote/github/test/github_teams_multiple/results.golden.json
  pkg/remote/github/test/github_teams_multiple/schema.golden.json
  pkg/resource/github/deserializer/github_team_deserializer.go
  pkg/resource/github/github_team.go
  pkg/resource/github/github_team_ext.go
  pkg/resource/github/github_team_ext_test.go
  pkg/resource/github/github_team_test.go
  pkg/resource/github/testdata/acc/github_team/.terraform.lock.hcl
  pkg/resource/github/testdata/acc/github_team/terraform.tf
Labels: kind/enhancement

#292 Allow to use a whole local directory as IaC source
  doc/cmd/scan/iac_source.md
  pkg/iac/terraform/state/enumerator/file.go
  pkg/iac/terraform/state/enumerator/file_test.go
  pkg/iac/terraform/state/enumerator/state_enumerator.go
  pkg/iac/terraform/state/enumerator/testdata/invalid_symlink/invalid
  pkg/iac/terraform/state/enumerator/testdata/states/route53/directory/route53.state
  pkg/iac/terraform/state/enumerator/testdata/states/s3/terraform.tfstate
  pkg/iac/terraform/state/enumerator/testdata/states/symlink-to-s3-folder
  pkg/iac/terraform/state/enumerator/testdata/states/symlink.tfstate
  pkg/iac/terraform/state/enumerator/testdata/states/terraform.tfstate
  pkg/iac/terraform/state/enumerator/testdata/states/terraform.tfstate.backup
  pkg/iac/terraform/state/enumerator/testdata/symlink
  pkg/iac/terraform/state/terraform_state_reader_acc_test.go
  pkg/iac/terraform/state/testdata/acc/multiple_states/route53/.terraform.lock.hcl
  pkg/iac/terraform/state/testdata/acc/multiple_states/route53/terraform.tf
  pkg/iac/terraform/state/testdata/acc/multiple_states/s3/.terraform.lock.hcl
  pkg/iac/terraform/state/testdata/acc/multiple_states/s3/terraform.tf
  pkg/iac/terraform/state/testdata/acc/multiple_states_local/.gitignore
  pkg/iac/terraform/state/testdata/acc/multiple_states_local/route53/.terraform.lock.hcl
  pkg/iac/terraform/state/testdata/acc/multiple_states_local/route53/terraform.tf
  pkg/iac/terraform/state/testdata/acc/multiple_states_local/s3/.terraform.lock.hcl
  pkg/iac/terraform/state/testdata/acc/multiple_states_local/s3/terraform.tf
Labels: kind/enhancement
