Repository snyk/driftctl, pull requests merged in 2021-07, with the labels that each got.

#774 Split ec2_ebs_volume_supplier
  pkg/remote/aws/ec2_ebs_volume_enumerator.go
  pkg/remote/aws/ec2_ebs_volume_supplier.go
  pkg/remote/aws/ec2_ebs_volume_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/ec2_ebs_volume_empty/schema.golden.json
  pkg/remote/aws/test/ec2_ebs_volume_multiple/schema.golden.json
  pkg/remote/ec2_scanner_test.go
  pkg/remote/test/aws_ec2_ebs_volume_empty/results.golden.json
  pkg/remote/test/aws_ec2_ebs_volume_multiple/aws_ebs_volume-vol-01ddc91d3d9d1318b.res.golden.json
  pkg/remote/test/aws_ec2_ebs_volume_multiple/aws_ebs_volume-vol-081c7272a57a09db1.res.golden.json
  pkg/remote/test/aws_ec2_ebs_volume_multiple/results.golden.json
Labels: kind/maintenance

#775 Split ec2_ebs_snapshot_supplier
  pkg/remote/aws/ec2_ebs_snapshot_enumerator.go
  pkg/remote/aws/ec2_ebs_snapshot_supplier.go
  pkg/remote/aws/ec2_ebs_snapshot_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/ec2_ebs_snapshot_empty/schema.golden.json
  pkg/remote/aws/test/ec2_ebs_snapshot_multiple/schema.golden.json
  pkg/remote/ec2_scanner_test.go
  pkg/remote/test/aws_ec2_ebs_snapshot_empty/results.golden.json
  pkg/remote/test/aws_ec2_ebs_snapshot_multiple/aws_ebs_snapshot-snap-00672558cecd93a61.res.golden.json
  pkg/remote/test/aws_ec2_ebs_snapshot_multiple/aws_ebs_snapshot-snap-0c509a2a880d95a39.res.golden.json
  pkg/remote/test/aws_ec2_ebs_snapshot_multiple/results.golden.json
Labels: kind/maintenance

#776 Split ec2_eip_supplier
  pkg/remote/aws/ec2_eip_enumerator.go
  pkg/remote/aws/ec2_eip_supplier.go
  pkg/remote/aws/ec2_eip_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/ec2_eip_empty/schema.golden.json
  pkg/remote/aws/test/ec2_eip_multiple/schema.golden.json
  pkg/remote/ec2_scanner_test.go
  pkg/remote/test/aws_ec2_eip_empty/results.golden.json
  pkg/remote/test/aws_ec2_eip_multiple/aws_eip-eipalloc-017d5267e4dda73f1.res.golden.json
  pkg/remote/test/aws_ec2_eip_multiple/aws_eip-eipalloc-0cf714dc097c992cc.res.golden.json
  pkg/remote/test/aws_ec2_eip_multiple/results.golden.json
Labels: kind/maintenance

#762 Split ec2_ami_supplier
  pkg/remote/aws/ec2_ami_enumerator.go
  pkg/remote/aws/ec2_ami_supplier.go
  pkg/remote/aws/ec2_ami_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/ec2_ami_empty/schema.golden.json
  pkg/remote/aws/test/ec2_ami_multiple/schema.golden.json
  pkg/remote/ec2_scanner_test.go
  pkg/remote/test/aws_ec2_ami_empty/results.golden.json
  pkg/remote/test/aws_ec2_ami_multiple/aws_ami-ami-025962fd8b456731f.res.golden.json
  pkg/remote/test/aws_ec2_ami_multiple/aws_ami-ami-03a578b46f4c3081b.res.golden.json
  pkg/remote/test/aws_ec2_ami_multiple/results.golden.json
Labels: kind/maintenance

#763 Split ec2_key_pair_supplier
  pkg/remote/aws/ec2_key_pair_enumerator.go
  pkg/remote/aws/ec2_key_pair_supplier.go
  pkg/remote/aws/ec2_key_pair_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/ec2_key_pair_empty/schema.golden.json
  pkg/remote/aws/test/ec2_key_pair_multiple/schema.golden.json
  pkg/remote/ec2_scanner_test.go
  pkg/remote/test/aws_ec2_key_pair_empty/results.golden.json
  pkg/remote/test/aws_ec2_key_pair_multiple/aws_key_pair-bar.res.golden.json
  pkg/remote/test/aws_ec2_key_pair_multiple/aws_key_pair-test.res.golden.json
  pkg/remote/test/aws_ec2_key_pair_multiple/results.golden.json
Labels: kind/maintenance

#778 Split ec2_eip_association_supplier
  pkg/remote/aws/ec2_eip_association_enumerator.go
  pkg/remote/aws/ec2_eip_association_supplier.go
  pkg/remote/aws/ec2_eip_association_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/ec2_eip_association_empty/schema.golden.json
  pkg/remote/aws/test/ec2_eip_association_single/schema.golden.json
  pkg/remote/ec2_scanner_test.go
  pkg/remote/test/aws_ec2_eip_association_empty/results.golden.json
  pkg/remote/test/aws_ec2_eip_association_single/aws_eip_association-eipassoc-0e9a7356e30f0c3d1.res.golden.json
  pkg/remote/test/aws_ec2_eip_association_single/results.golden.json
Labels: kind/maintenance

#779 Split ec2_instance_supplier
  pkg/remote/aws/ec2_instance_detail_fetcher.go
  pkg/remote/aws/ec2_instance_enumerator.go
  pkg/remote/aws/ec2_instance_supplier.go
  pkg/remote/aws/ec2_instance_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/ec2_instance_empty/schema.golden.json
  pkg/remote/aws/test/ec2_instance_multiple/schema.golden.json
  pkg/remote/aws/test/ec2_instance_terminated/schema.golden.json
  pkg/remote/ec2_scanner_test.go
  pkg/remote/test/aws_ec2_instance_empty/results.golden.json
  pkg/remote/test/aws_ec2_instance_multiple/aws_instance-i-010376047a71419f1.res.golden.json
  pkg/remote/test/aws_ec2_instance_multiple/aws_instance-i-0d3650a23f4e45dc0.res.golden.json
  pkg/remote/test/aws_ec2_instance_multiple/results.golden.json
  pkg/remote/test/aws_ec2_instance_terminated/aws_instance-i-0a3a7ed51ae2b4fa0.res.golden.json
  pkg/remote/test/aws_ec2_instance_terminated/aws_instance-i-0e1543baf4f2cd990.res.golden.json
  pkg/remote/test/aws_ec2_instance_terminated/results.golden.json
Labels: kind/maintenance

#777 split Github team membership supplier
  pkg/remote/github/github_team_membership_enumerator.go
  pkg/remote/github/github_team_membership_supplier.go
  pkg/remote/github/github_team_membership_supplier_test.go
  pkg/remote/github/init.go
  pkg/remote/github/test/github_team_membership_empty/schema.golden.json
  pkg/remote/github/test/github_team_membership_multiple/schema.golden.json
  pkg/remote/github_team_membership_scanner_test.go
  pkg/remote/test/github_team_membership_empty/results.golden.json
  pkg/remote/test/github_team_membership_multiple/github_team_membership-4570529_driftctl-acceptance-tester.res.golden.json
  pkg/remote/test/github_team_membership_multiple/github_team_membership-4570529_wbeuil.res.golden.json
  pkg/remote/test/github_team_membership_multiple/results.golden.json
  pkg/remote/test/github_team_membership_multiple/terraform.tf
Labels: kind/maintenance

#765 Split route53_zone_supplier
  pkg/remote/aws/init.go
  pkg/remote/aws/route53_zone_enumerator.go
  pkg/remote/aws/route53_zone_supplier.go
  pkg/remote/aws/route53_zone_supplier_test.go
  pkg/remote/route53_scanner_test.go
  pkg/remote/test/route53_zone_empty/results.golden.json
  pkg/remote/test/route53_zone_empty/schema.golden.json
  pkg/remote/test/route53_zone_multiples/aws_route53_zone-Z01804312AV8PHE3C43AD.res.golden.json
  pkg/remote/test/route53_zone_multiples/aws_route53_zone-Z01809283VH9BBALZHO7B.res.golden.json
  pkg/remote/test/route53_zone_multiples/aws_route53_zone-Z01874941AR1TCGV5K65C.res.golden.json
  pkg/remote/test/route53_zone_multiples/results.golden.json
  pkg/remote/test/route53_zone_multiples/schema.golden.json
  pkg/remote/test/route53_zone_multiples/terraform.tf
  pkg/remote/test/route53_zone_single/aws_route53_zone-Z08068311RGDXPHF8KE62.res.golden.json
  pkg/remote/test/route53_zone_single/aws_route53_zone-Z093553112BLINKY4N57.res.golden.json
  pkg/remote/test/route53_zone_single/results.golden.json
  pkg/remote/test/route53_zone_single/schema.golden.json
  pkg/remote/test/route53_zone_single/terraform.tf
  pkg/remote/test/route53_zone_with_no_record/results.golden.json
  pkg/remote/test/route53_zone_with_no_record/schema.golden.json
Labels: kind/maintenance

#671 Add a way to override s3 config/profile with env var
  pkg/envproxy/env_proxy.go
  pkg/envproxy/env_proxy_test.go
  pkg/iac/terraform/state/backend/s3_reader.go
  pkg/iac/terraform/state/backend/s3_reader_test.go
  pkg/iac/terraform/state/enumerator/s3.go
  pkg/iac/terraform/state/enumerator/s3_test.go
Labels: kind/enhancement

#796 Fix bucket policy return err when no policy exist
  pkg/remote/aws/repository/s3_repository.go
  pkg/remote/aws/repository/s3_repository_test.go
Labels: kind/bug

#798 Fix enumeration errors not handled
  pkg/remote/ec2_scanner_test.go
  pkg/remote/kms_scanner_test.go
  pkg/remote/route53_scanner_test.go
  pkg/remote/s3_scanner_test.go
  pkg/remote/scanner.go
  pkg/remote/test/aws_ec2_ami_list/results.golden.json
  pkg/remote/test/aws_ec2_default_route_table_list/results.golden.json
  pkg/remote/test/aws_ec2_default_subnet_list/results.golden.json
  pkg/remote/test/aws_ec2_ebs_snapshot_list/results.golden.json
  pkg/remote/test/aws_ec2_ebs_volume_list/results.golden.json
  pkg/remote/test/aws_ec2_eip_association_list/results.golden.json
  pkg/remote/test/aws_ec2_eip_list/results.golden.json
  pkg/remote/test/aws_ec2_instance_list/results.golden.json
  pkg/remote/test/aws_ec2_internet_gateway_list/results.golden.json
  pkg/remote/test/aws_ec2_key_pair_list/results.golden.json
  pkg/remote/test/aws_ec2_route_table_association_list/results.golden.json
  pkg/remote/test/aws_ec2_route_table_list/results.golden.json
  pkg/remote/test/aws_ec2_subnet_list/results.golden.json
  pkg/remote/test/aws_kms_alias_list/results.golden.json
  pkg/remote/test/aws_kms_key_list/results.golden.json
  pkg/remote/test/s3_bucket_list/results.golden.json
Labels: kind/bug

#809 Fix kms_key crash
  pkg/remote/aws/repository/kms_repository.go
  pkg/remote/aws/repository/kms_repository_test.go
  pkg/remote/common/details_fetcher.go
Labels: kind/bug

#821 Split iam policy supplier
  pkg/remote/aws/iam_policy_enumerator.go
  pkg/remote/aws/iam_policy_supplier.go
  pkg/remote/aws/iam_policy_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/iam_policy_empty/schema.golden.json
  pkg/remote/aws/test/iam_policy_multiple/schema.golden.json
  pkg/remote/iam_scanner_test.go
  pkg/remote/test/iam_policy_empty/results.golden.json
  pkg/remote/test/iam_policy_multiple/aws_iam_policy-arn_aws_iam__929327065333_policy_policy-0.res.golden.json
  pkg/remote/test/iam_policy_multiple/aws_iam_policy-arn_aws_iam__929327065333_policy_policy-1.res.golden.json
  pkg/remote/test/iam_policy_multiple/aws_iam_policy-arn_aws_iam__929327065333_policy_policy-2.res.golden.json
  pkg/remote/test/iam_policy_multiple/results.golden.json
Labels: kind/maintenance

#830 Use SupportedType() in enumerator
  pkg/remote/aws/route53_record_enumerator.go
  pkg/remote/aws/route53_zone_enumerator.go
  pkg/remote/aws/vpc_default_security_group_enumerator.go
  pkg/remote/aws/vpc_security_group_enumerator.go
Labels: kind/maintenance

#827 Split iam user
  pkg/remote/aws/iam_user_enumerator.go
  pkg/remote/aws/iam_user_supplier.go
  pkg/remote/aws/iam_user_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/iam_user_empty/schema.golden.json
  pkg/remote/aws/test/iam_user_multiple/schema.golden.json
  pkg/remote/iam_scanner_test.go
  pkg/remote/test/iam_user_empty/results.golden.json
  pkg/remote/test/iam_user_multiple/aws_iam_user-test-driftctl-0.res.golden.json
  pkg/remote/test/iam_user_multiple/aws_iam_user-test-driftctl-1.res.golden.json
  pkg/remote/test/iam_user_multiple/aws_iam_user-test-driftctl-2.res.golden.json
  pkg/remote/test/iam_user_multiple/results.golden.json
  pkg/remote/test/iam_user_multiple/terraform.tf
Labels: kind/maintenance

#828 Split iam_user_policy_supplier
  pkg/remote/aws/iam_user_policy_enumerator.go
  pkg/remote/aws/iam_user_policy_supplier.go
  pkg/remote/aws/iam_user_policy_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/iam_user_policy_empty/schema.golden.json
  pkg/remote/aws/test/iam_user_policy_multiple/schema.golden.json
  pkg/remote/iam_scanner_test.go
  pkg/remote/test/iam_user_policy_empty/results.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer2_test.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer2_test2.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer2_test22.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer2_test23.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer2_test24.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer2_test3.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer2_test4.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test2.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test22.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test23.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test24.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test3.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test32.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test33.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test34.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer3_test4.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer_test.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer_test2.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer_test3.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/aws_iam_user_policy-loadbalancer_test4.res.golden.json
  pkg/remote/test/iam_user_policy_multiple/main.tf
  pkg/remote/test/iam_user_policy_multiple/results.golden.json
Labels: kind/maintenance

#835 Remove unnecessary ec2_instance_details_fetcher
  pkg/remote/aws/ec2_instance_details_fetcher.go
  pkg/remote/aws/init.go
  pkg/remote/ec2_scanner_test.go
Labels: kind/maintenance

#833 Split iam_role_supplier
  pkg/remote/aws/iam_role_enumerator.go
  pkg/remote/aws/iam_role_supplier.go
  pkg/remote/aws/iam_role_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/iam_role_empty/schema.golden.json
  pkg/remote/aws/test/iam_role_ignore_services_roles/schema.golden.json
  pkg/remote/aws/test/iam_role_multiple/schema.golden.json
  pkg/remote/iam_scanner_test.go
  pkg/remote/test/iam_role_empty/results.golden.json
  pkg/remote/test/iam_role_ignore_services_roles/results.golden.json
  pkg/remote/test/iam_role_multiple/aws_iam_role-test_role_0.res.golden.json
  pkg/remote/test/iam_role_multiple/aws_iam_role-test_role_1.res.golden.json
  pkg/remote/test/iam_role_multiple/aws_iam_role-test_role_2.res.golden.json
  pkg/remote/test/iam_role_multiple/results.golden.json
  pkg/remote/test/iam_role_multiple/terraform.tf
Labels: kind/maintenance

#834 Split iam_access_key_supplier
  pkg/remote/aws/iam_access_key_details_fetcher.go
  pkg/remote/aws/iam_access_key_enumerator.go
  pkg/remote/aws/iam_access_key_supplier.go
  pkg/remote/aws/iam_access_key_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/iam_access_key_empty/schema.golden.json
  pkg/remote/aws/test/iam_access_key_multiple/schema.golden.json
  pkg/remote/iam_scanner_test.go
  pkg/remote/test/iam_access_key_empty/results.golden.json
  pkg/remote/test/iam_access_key_multiple/aws_iam_access_key-AKIA5QYBVVD223VWU32A-test-driftctl.res.golden.json
  pkg/remote/test/iam_access_key_multiple/aws_iam_access_key-AKIA5QYBVVD26EJME25D-test-driftctl2.res.golden.json
  pkg/remote/test/iam_access_key_multiple/aws_iam_access_key-AKIA5QYBVVD2QYI36UZP-test-driftctl.res.golden.json
  pkg/remote/test/iam_access_key_multiple/aws_iam_access_key-AKIA5QYBVVD2SWDFVVMG-test-driftctl2.res.golden.json
  pkg/remote/test/iam_access_key_multiple/results.golden.json
  pkg/remote/test/iam_access_key_multiple/terraform.tf
Labels: kind/maintenance

#837 Use proper provider version in ACC tests
  pkg/iac/terraform/state/testdata/acc/multiple_states/route53/terraform.tf
  pkg/iac/terraform/state/testdata/acc/multiple_states/s3/terraform.tf
  pkg/iac/terraform/state/testdata/acc/multiple_states_local/route53/terraform.tf
  pkg/iac/terraform/state/testdata/acc/multiple_states_local/s3/terraform.tf
  pkg/resource/aws/aws_eip_association_test.go
  pkg/resource/aws/aws_eip_test.go
  pkg/resource/aws/aws_iam_role_test.go
  pkg/resource/aws/aws_route_test.go
  pkg/resource/aws/testdata/acc/aws_eip/terraform.tf
  pkg/resource/aws/testdata/acc/aws_eip_association/mainf.tf
  pkg/resource/aws/testdata/acc/aws_iam_access_key/terraform.tf
  pkg/resource/aws/testdata/acc/aws_iam_policy_attachment/providers.tf
  pkg/resource/aws/testdata/acc/aws_instance/providers.tf
  pkg/resource/aws/testdata/acc/aws_route53_record/providers.tf
  pkg/resource/aws/testdata/acc/aws_route53_record_with_alias/providers.tf
  pkg/resource/aws/testdata/acc/aws_s3_bucket/providers.tf
Labels: kind/maintenance

#838 Fix goldenfile update
  test/test_diff.go
Labels: kind/maintenance

#840 Fix ipv6 route detail retrieval
  pkg/remote/aws/ec2_route_details_fetcher.go
Labels: kind/bug

#841 Split iam user policy attachment
  pkg/remote/aws/iam_user_policy_attachment_details_fetcher.go
  pkg/remote/aws/iam_user_policy_attachment_enumerator.go
  pkg/remote/aws/iam_user_policy_attachment_supplier.go
  pkg/remote/aws/iam_user_policy_attachment_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach-loadbalancer-arn_aws_iam__526954929923_policy_test-loadbalancer.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach-loadbalancer2-arn_aws_iam__526954929923_policy_test-loadbalancer2.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach-loadbalancer3-arn_aws_iam__526954929923_policy_test-loadbalancer3.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach2-loadbalancer-arn_aws_iam__526954929923_policy_test2-loadbalancer.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach2-loadbalancer2-arn_aws_iam__526954929923_policy_test2-loadbalancer2.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach2-loadbalancer3-arn_aws_iam__526954929923_policy_test2-loadbalancer3.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach3-loadbalancer-arn_aws_iam__526954929923_policy_test3-loadbalancer.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach3-loadbalancer2-arn_aws_iam__526954929923_policy_test3-loadbalancer2.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach3-loadbalancer3-arn_aws_iam__526954929923_policy_test3-loadbalancer3.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach4-loadbalancer-arn_aws_iam__526954929923_policy_test4-loadbalancer.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-attach4-loadbalancer2-arn_aws_iam__526954929923_policy_test4-loadbalancer2.res.golden.json
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/main.tf
  pkg/remote/aws/test/iam_user_policy_attachment_multiple/results.golden.json
  pkg/remote/iam_scanner_test.go
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-loadbalancer-arn_aws_iam__726421854799_policy_test-loadbalancer.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-loadbalancer2-arn_aws_iam__726421854799_policy_test-loadbalancer2.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test-loadbalancer3-arn_aws_iam__726421854799_policy_test-loadbalancer3.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test2-loadbalancer-arn_aws_iam__726421854799_policy_test2-loadbalancer.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test2-loadbalancer2-arn_aws_iam__726421854799_policy_test2-loadbalancer2.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test2-loadbalancer3-arn_aws_iam__726421854799_policy_test2-loadbalancer3.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test3-loadbalancer-arn_aws_iam__726421854799_policy_test3-loadbalancer.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test3-loadbalancer2-arn_aws_iam__726421854799_policy_test3-loadbalancer2.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test3-loadbalancer3-arn_aws_iam__726421854799_policy_test3-loadbalancer3.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test4-loadbalancer-arn_aws_iam__726421854799_policy_test4-loadbalancer.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test4-loadbalancer2-arn_aws_iam__726421854799_policy_test4-loadbalancer2.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/aws_iam_user_policy_attachment-test4-loadbalancer3-arn_aws_iam__726421854799_policy_test4-loadbalancer3.res.golden.json
  pkg/remote/test/iam_user_policy_attachment_multiple/main.tf
  pkg/remote/test/iam_user_policy_attachment_multiple/results.golden.json
Labels: kind/maintenance

#836 Split iam role policy supplier
  pkg/remote/aws/iam_role_policy_enumerator.go
  pkg/remote/aws/iam_role_policy_supplier.go
  pkg/remote/aws/iam_role_policy_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/iam_scanner_test.go
  pkg/remote/test/iam_role_policy_empty/results.golden.json
  pkg/remote/test/iam_role_policy_empty/schema.golden.json
  pkg/remote/test/iam_role_policy_multiple/aws_iam_role_policy-test_role_0_policy-role0-0.res.golden.json
  pkg/remote/test/iam_role_policy_multiple/aws_iam_role_policy-test_role_0_policy-role0-1.res.golden.json
  pkg/remote/test/iam_role_policy_multiple/aws_iam_role_policy-test_role_0_policy-role0-2.res.golden.json
  pkg/remote/test/iam_role_policy_multiple/aws_iam_role_policy-test_role_1_policy-role1-0.res.golden.json
  pkg/remote/test/iam_role_policy_multiple/aws_iam_role_policy-test_role_1_policy-role1-1.res.golden.json
  pkg/remote/test/iam_role_policy_multiple/aws_iam_role_policy-test_role_1_policy-role1-2.res.golden.json
  pkg/remote/test/iam_role_policy_multiple/results.golden.json
  pkg/remote/test/iam_role_policy_multiple/schema.golden.json
  pkg/remote/test/iam_role_policy_multiple/terraform.tf
Labels: kind/maintenance

#705 Implement in-memory store for analysis data
  pkg/cmd/scan.go
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/memstore/bucket.go
  pkg/memstore/buckets.go
  pkg/memstore/store.go
  pkg/memstore/store_test.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
Labels: kind/maintenance

#801 Split vpc_security_group_rule_supplier
  pkg/remote/aws/init.go
  pkg/remote/aws/init_test.go
  pkg/remote/aws/test/vpc_security_group_default_rules/schema.golden.json
  pkg/remote/aws/test/vpc_security_group_rule_empty/schema.golden.json
  pkg/remote/aws/test/vpc_security_group_rule_multiple/schema.golden.json
  pkg/remote/aws/vpc_security_group_rule_details_fetcher.go
  pkg/remote/aws/vpc_security_group_rule_enumerator.go
  pkg/remote/aws/vpc_security_group_rule_supplier_test.go
  pkg/remote/ec2_scanner_test.go
  pkg/remote/test/vpc_security_group_default_rules/aws_security_group_rule-sgrule-3820791514-1-1.2.0.0_16-0-0-0--1-sg-a74815c8-false--0-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_default_rules/aws_security_group_rule-sgrule-529352477-1-1.2.3.4_32-0-0-0--1-sg-a74815c8-false--0-egress.res.golden.json
  pkg/remote/test/vpc_security_group_default_rules/results.golden.json
  pkg/remote/test/vpc_security_group_rule_empty/results.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-1175318309-[0.0.0.0_0]-0--1-sg-0cc8b3c3c2851705a-false-0-egress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-1707973622-[0.0.0.0_0]-0--1-sg-0254c038e32f25530-false-0-egress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-2165103420-[5.6.7.0_24]-0--1-sg-0254c038e32f25530-false-0-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-2582518759-[1.2.0.0_16]-0--1-sg-0254c038e32f25530-false-0-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-2821752134-0-[___0]--1-sg-0254c038e32f25530-false-0-egress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-350400929-0-[___0]--1-sg-0cc8b3c3c2851705a-false-0-egress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-3587309474-0-tcp-sg-0254c038e32f25530-false-sg-9e0204ff-65535-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-3970541193-0-tcp-sg-0254c038e32f25530-true-65535-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-453320892-[0.0.0.0_0]-443-tcp-sg-0cc8b3c3c2851705a-false-443-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-674800228-0-[___0]--1-sg-0254c038e32f25530-false-0-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-850043874-[0.0.0.0_0]-5-sg-0cc8b3c3c2851705a-false-egress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/results.golden.json
Labels: kind/maintenance

#842 Use security group rule details fetcher
  pkg/remote/aws/init.go
Labels: kind/maintenance

#852 Add type to `route53_records` in enumerator
  pkg/remote/aws/route53_record_enumerator.go
Labels: kind/maintenance

#854 Add policy to `aws_sqs_queue_policy` enumerator
  pkg/remote/aws/repository/mock_SQSRepository.go
  pkg/remote/aws/repository/sqs_repository.go
  pkg/remote/aws/repository/sqs_repository_test.go
  pkg/remote/aws/sqs_queue_policy_enumerator.go
  pkg/remote/sqs_scanner_test.go
Labels: kind/maintenance

#858 Clarify HTML report input wording
  pkg/cmd/scan/output/assets/index.tmpl
  pkg/cmd/scan/output/testdata/output.html
  pkg/cmd/scan/output/testdata/output_empty.html
Labels: kind/enhancement

#853 Add origin to `aws_route` in enumerator
  pkg/remote/aws/ec2_route_enumerator.go
  pkg/remote/ec2_scanner_test.go
Labels: kind/maintenance

#857 Fix security group rule details fetcher
  pkg/remote/aws/vpc_security_group_rule_details_fetcher.go
  pkg/remote/aws/vpc_security_group_rule_enumerator.go
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-1175318309-1-0.0.0.0_0-0--1-sg-0cc8b3c3c2851705a-false-0-egress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-1707973622-1-0.0.0.0_0-0--1-sg-0254c038e32f25530-false-0-egress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-2165103420-1-5.6.7.0_24-0--1-sg-0254c038e32f25530-false-0-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-2582518759-1-1.2.0.0_16-0--1-sg-0254c038e32f25530-false-0-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-2821752134-0-1-___0--1-sg-0254c038e32f25530-false-0-egress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-350400929-0-1-___0--1-sg-0cc8b3c3c2851705a-false-0-egress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-453320892-1-0.0.0.0_0-443-tcp-sg-0cc8b3c3c2851705a-false-443-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-674800228-0-1-___0--1-sg-0254c038e32f25530-false-0-ingress.res.golden.json
  pkg/remote/test/vpc_security_group_rule_multiple/aws_security_group_rule-sgrule-850043874-1-0.0.0.0_0-5-sg-0cc8b3c3c2851705a-false-egress.res.golden.json
Labels: bug/regression, kind/bug

#851 Add path to `iam_role` in enumerator
  pkg/remote/aws/iam_role_enumerator.go
  pkg/remote/iam_scanner_test.go
Labels: kind/maintenance

#862 Add `allocation_id` to `nat_gw` and `eip_assoc`
  pkg/remote/aws/ec2_eip_association_enumerator.go
  pkg/remote/aws/ec2_nat_gateway_enumerator.go
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
  pkg/remote/aws/repository/mock_EC2Repository.go
  pkg/remote/ec2_scanner_test.go
Labels: kind/maintenance

#866 Update cli wording
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/testdata/output.txt
  pkg/cmd/scan/output/testdata/output_computed_fields.txt
  pkg/cmd/scan/output/testdata/output_empty_attributes.txt
  pkg/cmd/scan/output/testdata/output_json_fields.txt
  pkg/cmd/scan/output/testdata/output_stringer_resources.txt
Labels: kind/enhancement

#860 Add deep mode flag
  pkg/cmd/scan.go
  pkg/cmd/scan_test.go
  pkg/remote/scanner.go
  pkg/resource/aws/aws_ami_test.go
  pkg/resource/aws/aws_cloudfront_distribution_test.go
  pkg/resource/aws/aws_db_instance_test.go
  pkg/resource/aws/aws_db_subnet_group_test.go
  pkg/resource/aws/aws_dynamodb_table_test.go
  pkg/resource/aws/aws_ebs_snapshot_test.go
  pkg/resource/aws/aws_ebs_volume_test.go
  pkg/resource/aws/aws_ecr_repository_test.go
  pkg/resource/aws/aws_eip_association_test.go
  pkg/resource/aws/aws_eip_test.go
  pkg/resource/aws/aws_iam_access_key_test.go
  pkg/resource/aws/aws_iam_policy_attachment_test.go
  pkg/resource/aws/aws_iam_role_test.go
  pkg/resource/aws/aws_instance_test.go
  pkg/resource/aws/aws_internet_gateway_test.go
  pkg/resource/aws/aws_kms_alias_test.go
  pkg/resource/aws/aws_kms_key_test.go
  pkg/resource/aws/aws_lambda_event_source_mapping_test.go
  pkg/resource/aws/aws_nat_gateway_test.go
  pkg/resource/aws/aws_route53_health_check_test.go
  pkg/resource/aws/aws_route53_record_test.go
  pkg/resource/aws/aws_route_table_association_test.go
  pkg/resource/aws/aws_route_table_test.go
  pkg/resource/aws/aws_route_test.go
  pkg/resource/aws/aws_s3_bucket_test.go
  pkg/resource/aws/aws_security_group_rule_test.go
  pkg/resource/aws/aws_security_group_test.go
  pkg/resource/aws/aws_sns_topic_policy_test.go
  pkg/resource/aws/aws_sns_topic_subscription_test.go
  pkg/resource/aws/aws_sns_topic_test.go
  pkg/resource/aws/aws_sqs_queue_policy_test.go
  pkg/resource/aws/aws_sqs_queue_test.go
  pkg/resource/aws/aws_subnet_test.go
  pkg/resource/aws/aws_vpc_test.go
Labels: kind/enhancement, priority/1

#829 Setup Goreleaser
  .circleci/config.yml
  .gitignore
  .goreleaser.yml
  Makefile
  bin/.gitkeep
  go.sum
  scripts/build.sh
Labels: kind/maintenance

#872 Fix SQS queue policy crash
  pkg/remote/aws/sqs_queue_policy_enumerator.go
  pkg/remote/sqs_scanner_test.go
Labels: kind/bug

#881 Remove dead code since deep mode refactoring is complete
  pkg/cmd/scan.go
  pkg/remote/aws/init.go
  pkg/remote/cloudfront_scanner_test.go
  pkg/remote/dynamodb_scanner_test.go
  pkg/remote/ec2_scanner_test.go
  pkg/remote/ecr_scanner_test.go
  pkg/remote/github/init.go
  pkg/remote/github_branch_protection_scanner_test.go
  pkg/remote/github_membership_scanner_test.go
  pkg/remote/github_repository_scanner_test.go
  pkg/remote/github_team_membership_scanner_test.go
  pkg/remote/github_team_scanner_test.go
  pkg/remote/iam_scanner_test.go
  pkg/remote/kms_scanner_test.go
  pkg/remote/lambda_scanner_test.go
  pkg/remote/rds_scanner_test.go
  pkg/remote/remote.go
  pkg/remote/route53_scanner_test.go
  pkg/remote/s3_scanner_test.go
  pkg/remote/scanner.go
  pkg/remote/sns_scanner_test.go
  pkg/remote/sqs_scanner_test.go
  pkg/resource/resource_suppliers.go
Labels: kind/maintenance

#880 Move driftignore init outside driftctl
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/cmd/scan.go
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/filter/filter.go
  pkg/filter/mock_Filter.go
Labels: kind/maintenance

#884 Handle `destination_prefix_list_id` in `aws_route`
  pkg/middlewares/aws_route_table_expander.go
  pkg/middlewares/aws_route_table_expander_test.go
  pkg/remote/aws/ec2_route_enumerator.go
  pkg/resource/aws/aws_route.go
Labels: kind/bug

#890 Ignore terminated instance from enumeration
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
Labels: kind/bug

#891 Fix tag Name not displayed in deep mode
  pkg/resource/aws/aws_instance.go
  pkg/resource/aws/aws_route53_health_check.go
Labels: kind/bug
