Repository snyk/driftctl, pull requests merged in 2021-04, with the labels that each got.

#402 Fix aws_iam_policy_attachment false-positives
  pkg/iac/terraform/state/test/iam_role_policy_attachment/result.golden.json
  pkg/iac/terraform/state/test/iam_user_policy_attachment/result.golden.json
  pkg/resource/aws/aws_iam_policy_attachment_ext.go
  pkg/resource/aws/aws_iam_policy_attachment_test.go
  pkg/resource/aws/testdata/acc/aws_iam_policy_attachment/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_iam_policy_attachment/iam_policy_attachment.tf
  pkg/resource/aws/testdata/acc/aws_iam_policy_attachment/providers.tf
Labels: kind/bug, next-version/patch

#389 Add resource factory
  pkg/cmd/scan.go
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/middlewares/aws_bucket_policy_expander.go
  pkg/middlewares/aws_bucket_policy_expander_test.go
  pkg/middlewares/aws_instance_block_device.go
  pkg/middlewares/aws_instance_block_device_test.go
  pkg/middlewares/aws_route_table_expander.go
  pkg/middlewares/aws_route_table_expander_test.go
  pkg/middlewares/aws_sns_topic_policy_expander.go
  pkg/middlewares/aws_sns_topic_policy_expander_test.go
  pkg/middlewares/aws_sqs_queue_policy_expander.go
  pkg/middlewares/aws_sqs_queue_policy_expander_test.go
  pkg/middlewares/vpc_security_group_rules.go
  pkg/middlewares/vpc_security_group_rules_test.go
  pkg/resource/resource.go
  pkg/terraform/mock_ResourceFactory.go
  pkg/terraform/providers.go
  pkg/terraform/resource_factory.go
Labels: kind/maintenance

#404 Fix false positive on aws_route resources
  pkg/middlewares/aws_route_table_expander.go
  pkg/middlewares/aws_route_table_expander_test.go
Labels: kind/bug, next-version/patch

#410 Fix #409 do not list directory when using s3 as state backend
  pkg/iac/terraform/state/enumerator/s3.go
  pkg/iac/terraform/state/enumerator/s3_test.go
Labels: kind/bug

#406 Return explicit error on bad http status code
  pkg/iac/terraform/state/backend/http_reader.go
  pkg/iac/terraform/state/backend/http_reader_test.go
Labels: kind/bug

#413 Fix false positive on field InstanceInitiatedShutdownBehavior
  pkg/resource/aws/aws_instance.go
Labels: kind/bug

#388 Implement strict mode
  pkg/cmd/scan.go
  pkg/cmd/scan_test.go
  pkg/driftctl.go
  pkg/middlewares/aws_default_route_table_test.go
  pkg/middlewares/aws_defaults.go
  pkg/middlewares/aws_defaults_test.go
Labels: kind/enhancement, next-version/patch

#424 Fix issue 367 error reporting
  pkg/cmd/driftctl.go
Labels: next-version/patch

#425 Fix Typo Issue 367 error reporting
  pkg/cmd/driftctl.go
Labels: kind/documentation, next-version/patch

#428 Fix bug in default igw route middleware
  pkg/middlewares/aws_default_igw_route.go
  pkg/middlewares/aws_default_igw_route_test.go
Labels: kind/bug

#427 Use a deep link for known limitations docs
  pkg/analyser/analyzer.go
Labels: kind/enhancement

#432 Rename total_drifted to total_changed in JSON testdata
  pkg/analyser/testdata/input.json
Labels: kind/maintenance

#430 Update README.md
  README.md
Labels: kind/documentation

#414 Publish driftctl to Arch user repository
  .circleci/config.yml
  README.md
Labels: kind/maintenance

#447 Disable useless error wrappings
  pkg/driftctl.go
Labels: kind/maintenance

#361 Detect & exclude unsupported Terraform versions
  pkg/iac/terraform/state/terraform_state_reader.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/testdata/v4/invalid_version.tfstate
  pkg/iac/terraform/state/testdata/v4/supported_version.tfstate
  pkg/iac/terraform/state/testdata/v4/unsupported_version.tfstate
  pkg/iac/terraform/state/versions.go
  pkg/iac/terraform/state/versions_test.go
Labels: kind/enhancement

#452 Replace Sentry message by debug log
  main.go
Labels: kind/bug, priority/2

#448 Resume progress bar after timeout
  pkg/output/progress.go
  pkg/output/progress_test.go
Labels: kind/bug, priority/2

#449 Enforce one occurrence of filter flag
  pkg/cmd/scan.go
  pkg/cmd/scan_test.go
Labels: kind/bug, priority/2

#464 Fix version check lambda version bump
  .circleci/config.yml
Labels: kind/maintenance

#465 Add telemetry
  pkg/cmd/driftctl.go
  pkg/cmd/scan.go
  pkg/driftctl.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
Labels: kind/enhancement

#473 Display ec2 instance name when tag name exist
  pkg/resource/aws/aws_instance_ext.go
Labels: kind/enhancement, priority/2

#407 Fix body reader of http backend
  pkg/http/client.go
  pkg/http/mock_HTTPClient.go
  pkg/iac/terraform/state/backend/backend.go
  pkg/iac/terraform/state/backend/http_reader.go
  pkg/iac/terraform/state/backend/http_reader_test.go
Labels: kind/bug, priority/0

#467 Telemetry duration
  pkg/analyser/analysis.go
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
Labels: kind/maintenance

#435 Add a extra test case for the strict mode
  pkg/driftctl_test.go
  test/result.go
Labels: kind/maintenance
