Repository snyk/driftctl, pull requests merged in 2021-01, with the labels that each got.

#28 Ability to ignore a single field on a given resource
  doc/cmd/scan/filter.md
  mocks/Filter.go
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/driftctl.go
  pkg/filter/driftignore.go
  pkg/filter/driftignore_test.go
  pkg/filter/testdata/drift_ignore_fields/.driftignore
  pkg/filter/testdata/drift_ignore_invalid_lines/.driftignore
  pkg/filter/testdata/drift_ignore_valid/.driftignore
  test/resource/resource.go
Labels: kind/enhancement

#61 Fix broken driftignore
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
Labels: bug/regression, kind/bug, priority/0

#64 add home support for docker image
  Dockerfile
  README.md
Labels: kind/bug

#65 Fix test execution failed on darwin
  pkg/terraform/provider_installer_test.go
Labels: kind/maintenance

#63 Add sentry error reporting
  go.mod
  go.sum
  main.go
  pkg/cmd/driftctl.go
Labels: kind/enhancement

#71 Remove previous tag from version string in make build
  scripts/build.sh
Labels: kind/bug

#76 Fix records that has the same FQDN
  pkg/iac/terraform/state/test/route53_record/result.golden.json
  pkg/iac/terraform/state/test/route53_record_multiples/result.golden.json
  pkg/middlewares/route53_records_test.go
  pkg/remote/aws/route53_record_supplier_test.go
  pkg/remote/aws/test/route53_record_explicit_subdomain/aws_route53_record-Z06486383UC8WYSBZTWFM__test2.foo-2.com_A.res.golden.json
  pkg/remote/aws/test/route53_record_explicit_subdomain/aws_route53_record-Z06486383UC8WYSBZTWFM_test0_A.res.golden.json
  pkg/remote/aws/test/route53_record_explicit_subdomain/aws_route53_record-Z06486383UC8WYSBZTWFM_test1.foo-2.com_A.res.golden.json
  pkg/remote/aws/test/route53_record_explicit_subdomain/main.tf
  pkg/remote/aws/test/route53_record_explicit_subdomain/results.golden.json
  pkg/resource/aws/aws_route53_record.go
  pkg/resource/aws/aws_route53_record_ext.go
  pkg/resource/aws/aws_route53_record_test.go
  pkg/resource/aws/testdata/acc/aws_route53_record/route53.tf
Labels: kind/bug

#78 Make driftignore fields case-insensitive
  doc/cmd/scan/filter.md
  pkg/filter/driftignore.go
  pkg/filter/testdata/drift_ignore_fields/.driftignore
Labels: kind/bug

#67 Several improvements on acceptance tests
  pkg/resource/aws/aws_instance_test.go
  pkg/resource/aws/testdata/acc/aws_instance/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_route53_record/.terraform.lock.hcl
  test/acceptance/testing.go
Labels: kind/maintenance

#81 Fix crash for buckets in us-east-1
  pkg/remote/aws/s3_bucket_supplier.go
  pkg/resource/aws/aws_s3_bucket_test.go
  pkg/resource/aws/testdata/acc/aws_s3_bucket/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_s3_bucket/providers.tf
  pkg/resource/aws/testdata/acc/aws_s3_bucket/s3.tf
Labels: kind/bug, priority/0

#89 Update README with Homebrew installation guidelines with its badge
  README.md
Labels: kind/documentation

#92 Start by reading IaC before enumerate cloud resources
  pkg/driftctl.go
Labels: kind/enhancement

#91 Document what exactly is shared when using --error-reporting
  doc/README.md
  doc/cmd/flags/error-reporting.md
  doc/cmd/flags/img/sentry.png
Labels: kind/documentation

#99 Homebrew bump driftctl formula CircleCI
  .circleci/config.yml
Labels: kind/maintenance

#29 Handle alert during execution
  doc/contributing/tests.md
  pkg/alerter/alert.go
  pkg/alerter/alerter.go
  pkg/alerter/alerter_test.go
  pkg/analyser/analysis.go
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/analyser/testdata/input.json
  pkg/analyser/testdata/output.json
  pkg/cmd/scan.go
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/console_test.go
  pkg/cmd/scan/output/json_test.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output.json
  pkg/cmd/scan/output/testdata/output_computed_fields.json
  pkg/cmd/scan/output/testdata/output_computed_fields.txt
  pkg/driftctl.go
  pkg/remote/aws/init.go
  pkg/remote/remote.go
  pkg/resource/aws/aws_instance_test.go
  pkg/scanner.go
  test/acceptance/result.go
  test/resource/resource.go
Labels: kind/enhancement

#104 Remove useless exports in VPC supplier
  pkg/remote/aws/vpc_supplier.go
Labels: kind/maintenance

#106 Fix wrong documentation telling driftctl needs write access to S3 state files
  doc/cmd/scan/iac_source.md
Labels: kind/documentation

#115 Fix a weakness in analyzer
  pkg/analyser/analyzer.go
Labels: kind/bug

#120 Move documentation section above in the readme
  README.md
Labels: kind/documentation

#114 Display analysis summary when infra not in sync in acc tests
  test/acceptance/result.go
Labels: kind/maintenance

#112 Doc to use our custom role CloudFormation template
  doc/cmd/scan/supported_resources/aws.md
Labels: kind/documentation

#122 Add aws_default_security_group
  doc/cmd/scan/supported_resources/aws.md
  pkg/iac/deserializers.go
  pkg/middlewares/vpc_security_group_default.go
  pkg/middlewares/vpc_security_group_default_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/test/vpc_security_group_empty/results.aws_default_security_group.golden.json
  pkg/remote/aws/test/vpc_security_group_empty/results.aws_security_group.golden.json
  pkg/remote/aws/test/vpc_security_group_empty/results.golden.json
  pkg/remote/aws/test/vpc_security_group_multiple/aws_default_security_group-sg-9e0204ff.res.golden.json
  pkg/remote/aws/test/vpc_security_group_multiple/aws_security_group-sg-0254c038e32f25530.res.golden.json
  pkg/remote/aws/test/vpc_security_group_multiple/aws_security_group-sg-9e0204ff.res.golden.json
  pkg/remote/aws/test/vpc_security_group_multiple/results.aws_default_security_group.golden.json
  pkg/remote/aws/test/vpc_security_group_multiple/results.aws_security_group.golden.json
  pkg/remote/aws/test/vpc_security_group_multiple/results.golden.json
  pkg/remote/aws/test/vpc_security_group_multiple/terraform.tf
  pkg/remote/aws/vpc_security_group_rule_supplier.go
  pkg/remote/aws/vpc_security_group_supplier.go
  pkg/remote/aws/vpc_security_group_supplier_test.go
  pkg/resource/aws/aws_default_security_group.go
  pkg/resource/aws/aws_default_security_group_ext.go
  pkg/resource/aws/aws_security_group_test.go
  pkg/resource/aws/deserializer/default_security_group_deserializer.go
  pkg/resource/aws/testdata/acc/aws_security_group/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_security_group/terraform.tf
Labels: kind/enhancement

#140 Add middleware for default gateway route
  pkg/driftctl.go
  pkg/middlewares/aws_default_igw_route.go
  pkg/middlewares/aws_default_igw_route_test.go
Labels: kind/enhancement

#133 Driftctl completion command
  doc/README.md
  doc/cmd/completion/script.md
  pkg/cmd/completion.go
  pkg/cmd/completion_test.go
  pkg/cmd/driftctl.go
  pkg/cmd/driftctl_test.go
Labels: kind/enhancement

#141 only send one alert for computed fieds
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output_computed_fields.json
  pkg/cmd/scan/output/testdata/output_computed_fields.txt
Labels: kind/maintenance

#149 Fix false positive drift on aws_iam_user
  pkg/iac/terraform/state/test/iam_user_multiple/terraform.tfstate
  pkg/resource/aws/aws_iam_user_ext.go
Labels: kind/bug

#153 Allow to override env vars for terraform operations in acc tests
  doc/contributing/tests.md
  test/acceptance/testing.go
  test/acceptance/testing_test.go
Labels: kind/maintenance

#155 bash completion doc fix
  doc/cmd/completion/script.md
Labels: kind/documentation

#156 Return exit code 1 when infrastructure not in sync
  main.go
  pkg/cmd/driftctl.go
  pkg/cmd/errors/scan.go
  pkg/cmd/scan.go
  test/acceptance/testing.go
Labels: kind/enhancement

#158 Middleware to explode inline policy
  pkg/driftctl.go
  pkg/middlewares/aws_bucket_policy_expander.go
  pkg/middlewares/aws_bucket_policy_expander_test.go
Labels: kind/bug

#167 Make DCTL_NO_VERSION_CHECK accept any value
  doc/README.md
  pkg/cmd/driftctl.go
  pkg/cmd/driftctl_test.go
Labels: kind/enhancement

#171 hotfix for multiple computed alert being send
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
Labels: kind/bug, next-version/patch

#172 initial ROADMAP.md
  ROADMAP.md
Labels: kind/documentation

#166 Fix acceptance test issues
  doc/contributing/tests.md
  pkg/resource/aws/aws_instance_test.go
  pkg/resource/aws/aws_route53_record_test.go
  pkg/resource/aws/aws_s3_bucket_test.go
  pkg/resource/aws/testdata/acc/aws_instance/providers.tf
  pkg/resource/aws/testdata/acc/aws_internet_gateway/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_route53_record/providers.tf
  test/acceptance/result.go
  test/acceptance/testing.go
Labels: kind/maintenance
