Repository snyk/driftctl, pull requests merged in 2021-05, with the labels that each got.

#416 Add dynamic Terraform versions to acceptance tests
  pkg/iac/terraform/state/terraform_state_reader_acc_test.go
  pkg/resource/aws/aws_cloudfront_distribution_test.go
  pkg/resource/aws/aws_dynamodb_table_test.go
  pkg/resource/aws/aws_ecr_repository_test.go
  pkg/resource/aws/aws_instance_test.go
  pkg/resource/aws/aws_internet_gateway_test.go
  pkg/resource/aws/aws_kms_alias_test.go
  pkg/resource/aws/aws_kms_key_test.go
  pkg/resource/aws/aws_lambda_event_source_mapping_test.go
  pkg/resource/aws/aws_nat_gateway_test.go
  pkg/resource/aws/aws_route53_health_check_test.go
  pkg/resource/aws/aws_route53_record_test.go
  pkg/resource/aws/aws_route_table_association_test.go
  pkg/resource/aws/aws_route_table_test.go
  pkg/resource/aws/aws_route_test.go
  pkg/resource/aws/aws_s3_bucket_test.go
  pkg/resource/aws/aws_security_group_test.go
  pkg/resource/aws/aws_sns_topic_policy_test.go
  pkg/resource/aws/aws_sns_topic_subscription_test.go
  pkg/resource/aws/aws_sns_topic_test.go
  pkg/resource/aws/aws_sqs_queue_policy_test.go
  pkg/resource/aws/aws_sqs_queue_test.go
  pkg/resource/aws/aws_subnet_test.go
  pkg/resource/github/github_branch_protection_test.go
  pkg/resource/github/github_repository_test.go
  pkg/resource/github/github_team_membership_test.go
  pkg/resource/github/github_team_test.go
  test/acceptance/testing.go
Labels: kind/maintenance, priority/3

#458 Support for Terraform Cloud / Terraform Enterprise
  pkg/cmd/driftctl_test.go
  pkg/cmd/scan.go
  pkg/cmd/scan_test.go
  pkg/iac/supplier/supplier_test.go
  pkg/iac/terraform/state/backend/backend.go
  pkg/iac/terraform/state/backend/tfcloud_reader.go
  pkg/iac/terraform/state/backend/tfcloud_reader_test.go
Labels: kind/enhancement, priority/1

#483 Update sentry SDK to 0.10
  go.mod
  go.sum
Labels: kind/maintenance

#484 Fix build script broken on gox install
  scripts/build.sh
Labels: kind/maintenance

#485 Change jsondiff library
  go.mod
  go.sum
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output_json_fields.txt
Labels: kind/maintenance

#460 Introduce a new progress bar for state enumeration
  pkg/cmd/scan.go
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/iac/supplier/supplier.go
  pkg/iac/supplier/supplier_test.go
  pkg/iac/terraform/state/terraform_state_reader.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/output/progress.go
  pkg/output/progress_test.go
Labels: kind/bug, priority/2

#433 Create driftignore generator command
  pkg/analyser/analysis.go
  pkg/cmd/driftctl.go
  pkg/cmd/gen_driftignore.go
  pkg/cmd/gen_driftignore_test.go
  pkg/cmd/testdata/input_stdin_empty.json
  pkg/cmd/testdata/input_stdin_invalid.json
  pkg/cmd/testdata/input_stdin_valid.json
  pkg/cmd/testdata/output_stdin_empty.txt
  pkg/cmd/testdata/output_stdin_valid.txt
  pkg/cmd/testdata/output_stdin_valid_filter.txt
  pkg/cmd/testdata/output_stdin_valid_filter2.txt
Labels: kind/enhancement

#486 Move all AWS mocks to test/aws
  pkg/iac/terraform/state/backend/s3_reader_test.go
  pkg/iac/terraform/state/enumerator/s3_test.go
  pkg/remote/aws/iam_access_key_supplier_test.go
  pkg/remote/aws/iam_policy_supplier_test.go
  pkg/remote/aws/iam_role_policy_attachment_supplier_test.go
  pkg/remote/aws/iam_role_policy_supplier_test.go
  pkg/remote/aws/iam_role_supplier_test.go
  pkg/remote/aws/iam_user_policy_attachment_supplier_test.go
  pkg/remote/aws/iam_user_policy_supplier_test.go
  pkg/remote/aws/iam_user_supplier_test.go
  pkg/remote/aws/internet_gateway_supplier_test.go
  pkg/remote/aws/nat_gateway_supplier_test.go
  pkg/remote/aws/repository/cloudfront_repository_test.go
  pkg/remote/aws/repository/dynamodb_repository_test.go
  pkg/remote/aws/repository/ecr_repository_test.go
  pkg/remote/aws/repository/kms_repository_test.go
  pkg/remote/aws/repository/route53_repository_test.go
  pkg/remote/aws/repository/s3_repository_test.go
  pkg/remote/aws/repository/sns_repository_test.go
  pkg/remote/aws/repository/sqs_repository_test.go
  pkg/remote/aws/route_supplier_test.go
  pkg/remote/aws/route_table_association_supplier_test.go
  pkg/remote/aws/route_table_supplier_test.go
  pkg/remote/aws/subnet_supplier_test.go
  pkg/remote/aws/vpc_security_group_rule_supplier_test.go
  pkg/remote/aws/vpc_security_group_supplier_test.go
  pkg/remote/aws/vpc_supplier_test.go
  test/aws/README.md
  test/aws/cloudfront.go
  test/aws/dynamodb.go
  test/aws/ecr.go
  test/aws/kms.go
  test/aws/mock_FakeCloudFront.go
  test/aws/mock_FakeDynamoDB.go
  test/aws/mock_FakeEC2.go
  test/aws/mock_FakeECR.go
  test/aws/mock_FakeIAM.go
  test/aws/mock_FakeKMS.go
  test/aws/mock_FakeRequestFailure.go
  test/aws/mock_FakeRoute53.go
  test/aws/mock_FakeS3.go
  test/aws/mock_FakeSNS.go
  test/aws/mock_FakeSQS.go
  test/aws/route53.go
  test/aws/sns.go
Labels: kind/maintenance

#471 Refacto `aws_s3_bucket`
  pkg/driftctl_test.go
  pkg/iac/terraform/state/test/s3_full/result.golden.json
  pkg/iac/terraform/state/test/unsupported_provider/result.golden.json
  pkg/middlewares/aws_bucket_policy_expander.go
  pkg/middlewares/aws_bucket_policy_expander_test.go
  pkg/middlewares/s3_bucket_acl.go
  pkg/middlewares/s3_bucket_acl_test.go
  pkg/resource/aws/aws_s3_bucket.go
  pkg/resource/aws/aws_s3_bucket_test.go
  pkg/resource/aws/metadatas.go
  pkg/resource/aws/testdata/acc/aws_s3_bucket/s3.tf
  pkg/resource/resource.go
Labels: kind/maintenance

#353 Limited glob support for enumerators
  go.mod
  go.sum
  pkg/iac/terraform/state/enumerator/file.go
  pkg/iac/terraform/state/enumerator/file_test.go
  pkg/iac/terraform/state/enumerator/glob.go
  pkg/iac/terraform/state/enumerator/s3.go
  pkg/iac/terraform/state/enumerator/s3_test.go
  pkg/iac/terraform/state/enumerator/testdata/states/lambda/lambda.tfstate
Labels: kind/enhancement, priority/2

#500 Add a missing line break in warning message
  pkg/iac/terraform/state/terraform_state_reader.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/versions.go
Labels: bug/regression, priority/0

#506 Report when no tfstate found in backend
  pkg/iac/terraform/state/enumerator/file.go
  pkg/iac/terraform/state/enumerator/file_test.go
  pkg/iac/terraform/state/enumerator/s3.go
  pkg/iac/terraform/state/enumerator/s3_test.go
  pkg/iac/terraform/state/enumerator/testdata/no_state_here/dummy.json
Labels: kind/bug, priority/1

#510 Fix deep links for providers authentication
  pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.txt
  pkg/cmd/scan/output/testdata/output_access_denied_alert_github.txt
  pkg/remote/resource_enumeration_error_handler.go
  pkg/remote/resource_enumeration_error_handler_test.go
Labels: kind/bug, priority/1

#511 Disable count in scan progress bar
  pkg/cmd/scan.go
Labels: kind/enhancement, priority/2

#507 Refacto github resources
  pkg/iac/terraform/state/test/github_branch_protection/result.golden.json
  pkg/iac/terraform/state/test/github_membership/result.golden.json
  pkg/iac/terraform/state/test/github_repository/result.golden.json
  pkg/iac/terraform/state/test/github_team/result.golden.json
  pkg/iac/terraform/state/test/github_team_membership/result.golden.json
  pkg/resource/github/github_branch_protection.go
  pkg/resource/github/github_membership.go
  pkg/resource/github/github_repository.go
  pkg/resource/github/github_team.go
  pkg/resource/github/github_team_membership.go
  pkg/resource/github/metadatas.go
  pkg/resource/resource.go
Labels: kind/maintenance

#508 Refacto aws_iam_access_key
  pkg/iac/terraform/state/test/iam_access_key_multiple/result.golden.json
  pkg/iac/terraform/state/test/module.iam_iam-user/result.golden.json
  pkg/resource/aws/aws_iam_access_key.go
  pkg/resource/aws/aws_iam_access_key_ext_test.go
  pkg/resource/aws/aws_iam_access_key_test.go
  pkg/resource/aws/metadatas.go
  pkg/resource/aws/testdata/acc/aws_iam_access_key/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_iam_access_key/terraform.tf
  pkg/resource/resource.go
Labels: kind/maintenance

#512 Fix iam policy attachment issues
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/middlewares/iam_policy_attachment_expander.go
  pkg/middlewares/iam_policy_attachment_expander_test.go
Labels: kind/bug

#523 Add internet_gateway to ec2_repository
  pkg/remote/aws/internet_gateway_supplier.go
  pkg/remote/aws/internet_gateway_supplier_test.go
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
  pkg/remote/aws/repository/mock_EC2Repository.go
  pkg/remote/aws/test/internet_gateway_multiple/aws_internet_gateway-igw-0184eb41aadc62d1c.res.golden.json
  pkg/remote/aws/test/internet_gateway_multiple/aws_internet_gateway-igw-025e25487b9ee553b.res.golden.json
  pkg/remote/aws/test/internet_gateway_multiple/aws_internet_gateway-igw-047b487f5c60fca99.res.golden.json
  pkg/remote/aws/test/internet_gateway_multiple/aws_internet_gateway-igw-0aa10b4e92738d8ed.res.golden.json
  pkg/remote/aws/test/internet_gateway_multiple/results.golden.json
Labels: kind/enhancement

#527 Issue 165: Add subnet_supplier to ec2_repository
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
  pkg/remote/aws/repository/mock_EC2Repository.go
  pkg/remote/aws/subnet_supplier.go
  pkg/remote/aws/subnet_supplier_test.go
Labels: kind/enhancement

#522 Add nat_gateways to ec2_repository
  pkg/remote/aws/nat_gateway_supplier.go
  pkg/remote/aws/nat_gateway_supplier_test.go
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
  pkg/remote/aws/repository/mock_EC2Repository.go
Labels: kind/enhancement

#533 Add route_supplier to ec2_repository
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
  pkg/remote/aws/repository/mock_EC2Repository.go
  pkg/remote/aws/route_supplier.go
  pkg/remote/aws/route_supplier_test.go
Labels: kind/enhancement

#534 Add route_table and route_table_association to ec2_repository
  pkg/remote/aws/route_table_association_supplier.go
  pkg/remote/aws/route_table_association_supplier_test.go
  pkg/remote/aws/route_table_supplier.go
  pkg/remote/aws/route_table_supplier_test.go
Labels: kind/enhancement

#535 Add vpc_supplier to ec2_repository
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
  pkg/remote/aws/repository/mock_EC2Repository.go
  pkg/remote/aws/vpc_supplier.go
  pkg/remote/aws/vpc_supplier_test.go
Labels: kind/enhancement

#536 Add vpc_security_group/_rule to ec2_repository
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
  pkg/remote/aws/repository/mock_EC2Repository.go
  pkg/remote/aws/vpc_security_group_rule_supplier.go
  pkg/remote/aws/vpc_security_group_rule_supplier_test.go
  pkg/remote/aws/vpc_security_group_supplier.go
  pkg/remote/aws/vpc_security_group_supplier_test.go
Labels: kind/enhancement

#501 Create driftignore generator command
  pkg/analyser/analysis.go
  pkg/cmd/driftctl.go
  pkg/cmd/gen_driftignore.go
  pkg/cmd/gen_driftignore_test.go
  pkg/cmd/scan.go
  pkg/cmd/testdata/input_stdin_empty.json
  pkg/cmd/testdata/input_stdin_invalid.json
  pkg/cmd/testdata/input_stdin_valid.json
  pkg/cmd/testdata/output_stdin_empty.txt
  pkg/cmd/testdata/output_stdin_valid.txt
  pkg/cmd/testdata/output_stdin_valid_filter.txt
  pkg/cmd/testdata/output_stdin_valid_filter2.txt
Labels: kind/enhancement, priority/1

#545 Fix aws_db_instance false-positives
  pkg/resource/aws/aws_db_instance_ext.go
  pkg/resource/aws/aws_db_instance_test.go
  pkg/resource/aws/testdata/acc/aws_db_instance/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_db_instance/db_instance.tf
Labels: kind/bug

#438 Create iam_repository
  pkg/remote/aws/iam_access_key_supplier.go
  pkg/remote/aws/iam_access_key_supplier_test.go
  pkg/remote/aws/iam_policy_supplier.go
  pkg/remote/aws/iam_policy_supplier_test.go
  pkg/remote/aws/iam_role_policy_attachment_supplier.go
  pkg/remote/aws/iam_role_policy_attachment_supplier_test.go
  pkg/remote/aws/iam_role_policy_supplier.go
  pkg/remote/aws/iam_role_policy_supplier_test.go
  pkg/remote/aws/iam_role_supplier.go
  pkg/remote/aws/iam_role_supplier_test.go
  pkg/remote/aws/iam_user_policy_attachment_supplier.go
  pkg/remote/aws/iam_user_policy_attachment_supplier_test.go
  pkg/remote/aws/iam_user_policy_supplier.go
  pkg/remote/aws/iam_user_policy_supplier_test.go
  pkg/remote/aws/iam_user_supplier.go
  pkg/remote/aws/iam_user_supplier_test.go
  pkg/remote/aws/repository/iam_repository.go
  pkg/remote/aws/repository/iam_repository_test.go
  pkg/remote/aws/repository/mock_IAMRepository.go
  pkg/remote/aws/test/iam_access_key_multiple/results.golden.json
Labels: kind/maintenance

#567 Remove terraform installation step in CI
  .circleci/config.yml
Labels: kind/maintenance

#557 Ensure enumerated paths are not folders
  pkg/iac/terraform/state/enumerator/file_test.go
  pkg/iac/terraform/state/enumerator/glob.go
  pkg/iac/terraform/state/enumerator/s3_test.go
  pkg/iac/terraform/state/enumerator/testdata/edge_cases/terraform.tfstate/terraform.tfstate
Labels: kind/bug
