Repository snyk/driftctl, pull requests merged in 2021-10, with the labels that each got.

#1016 Read provider version from .terraform.lock.hcl lock file when possible
  go.mod
  go.sum
  pkg/cmd/driftctl.go
  pkg/cmd/scan.go
  pkg/cmd/scan_test.go
  pkg/cmd/testdata/terraform_invalid.lock.hcl
  pkg/cmd/testdata/terraform_valid.lock.hcl
  pkg/remote/aws/init.go
  pkg/remote/aws/provider.go
  pkg/remote/azurerm/init.go
  pkg/remote/azurerm/provider.go
  pkg/remote/common/providers.go
  pkg/remote/github/init.go
  pkg/remote/github/provider.go
  pkg/remote/google/init.go
  pkg/remote/google/provider.go
  pkg/remote/terraform/provider.go
  pkg/terraform/lock/lockfile.go
  pkg/terraform/lock/lockfile_test.go
  pkg/terraform/lock/testdata/lockfile_empty.hcl
  pkg/terraform/lock/testdata/lockfile_invalid.hcl
  pkg/terraform/lock/testdata/lockfile_invalid_type-1.hcl
  pkg/terraform/lock/testdata/lockfile_invalid_type-3.hcl
  pkg/terraform/lock/testdata/lockfile_valid.hcl
Labels: kind/enhancement

#1082 Add azurerm virtual network
  go.mod
  go.sum
  pkg/remote/azurerm/azurerm_virtual_network_enumerator.go
  pkg/remote/azurerm/init.go
  pkg/remote/azurerm/repository/mock_NetworkRepository.go
  pkg/remote/azurerm/repository/mock_virtualNetworkClient.go
  pkg/remote/azurerm/repository/mock_virtualNetworksListAllPager.go
  pkg/remote/azurerm/repository/network.go
  pkg/remote/azurerm/repository/network_test.go
  pkg/remote/azurerm/repository/pager.go
  pkg/remote/azurerm/repository/storage.go
  pkg/remote/azurerm_network_scanner_test.go
  pkg/resource/azurerm/azurerm_virtual_network.go
  pkg/resource/azurerm/azurerm_virtual_network_test.go
  pkg/resource/azurerm/testdata/acc/azurerm_virtual_network/.terraform.lock.hcl
  pkg/resource/azurerm/testdata/acc/azurerm_virtual_network/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1086 Remove marks from values in the deserializer
  pkg/resource/deserializer.go
Labels: kind/bug

#1089 Add azurerm_route_table
  pkg/remote/azurerm/azurerm_route_table_enumerator.go
  pkg/remote/azurerm/init.go
  pkg/remote/azurerm/repository/mock_NetworkRepository.go
  pkg/remote/azurerm/repository/mock_routeTablesClient.go
  pkg/remote/azurerm/repository/mock_routeTablesListAllPager.go
  pkg/remote/azurerm/repository/network.go
  pkg/remote/azurerm/repository/network_test.go
  pkg/remote/azurerm_network_scanner_test.go
  pkg/resource/azurerm/azurerm_route_table.go
  pkg/resource/azurerm/azurerm_route_table_test.go
  pkg/resource/azurerm/metadata.go
  pkg/resource/azurerm/testdata/acc/azurerm_route_table/.terraform.lock.hcl
  pkg/resource/azurerm/testdata/acc/azurerm_route_table/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1078 Add azurerm_resource_group resource
  go.mod
  go.sum
  pkg/remote/azurerm/azurerm_resource_group_enumerator.go
  pkg/remote/azurerm/init.go
  pkg/remote/azurerm/repository/mock_ResourcesRepository.go
  pkg/remote/azurerm/repository/mock_resourcesClient.go
  pkg/remote/azurerm/repository/mock_resourcesListPager.go
  pkg/remote/azurerm/repository/resources.go
  pkg/remote/azurerm/repository/resources_test.go
  pkg/remote/azurerm_resources_scanner_test.go
  pkg/resource/azurerm/azurerm_resource_group.go
  pkg/resource/azurerm/azurerm_resource_group_test.go
  pkg/resource/azurerm/metadata.go
  pkg/resource/azurerm/testdata/acc/azurerm_resource_group/.terraform.lock.hcl
  pkg/resource/azurerm/testdata/acc/azurerm_resource_group/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1091 use codecov orb
  .circleci/config.yml
Labels: kind/maintenance
