Repository snyk/driftctl, pull requests merged in 2021-09, with the labels that each got.

#966 Remove options in output config
  pkg/cmd/scan.go
  pkg/cmd/scan/output/config.go
  pkg/cmd/scan/output/output.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan_test.go
Labels: kind/maintenance

#1012 Fix ordering inconsistency in console output
  pkg/cmd/scan/output/console.go
Labels: kind/maintenance

#1020 Fix crash in output when source is nil
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/html_test.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output.html
  pkg/cmd/scan/output/testdata/output.json
  pkg/cmd/scan/output/testdata/output.txt
  pkg/resource/resource.go
Labels: kind/bug, priority/0

#1017 Add original error message for scan errors
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output.html
  pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.txt
  pkg/cmd/scan/output/testdata/output_access_denied_alert_github.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert_github.txt
  pkg/remote/alerts/alerts.go
  pkg/remote/cloudfront_scanner_test.go
  pkg/remote/dynamodb_scanner_test.go
  pkg/remote/ec2_scanner_test.go
  pkg/remote/ecr_scanner_test.go
  pkg/remote/github_branch_protection_scanner_test.go
  pkg/remote/github_membership_scanner_test.go
  pkg/remote/github_repository_scanner_test.go
  pkg/remote/github_team_membership_scanner_test.go
  pkg/remote/github_team_scanner_test.go
  pkg/remote/google_storage_scanner_test.go
  pkg/remote/iam_scanner_test.go
  pkg/remote/kms_scanner_test.go
  pkg/remote/lambda_scanner_test.go
  pkg/remote/rds_scanner_test.go
  pkg/remote/resource_enumeration_error_handler_test.go
  pkg/remote/route53_scanner_test.go
  pkg/remote/s3_scanner_test.go
  pkg/remote/sns_scanner_test.go
  pkg/remote/sqs_scanner_test.go
Labels: kind/enhancement

#865 Allow multiple output flags for a single scan
  pkg/cmd/scan.go
  pkg/cmd/scan/output/config.go
  pkg/cmd/scan/output/output.go
  pkg/cmd/scan_test.go
  pkg/driftctl.go
Labels: kind/enhancement

#1013 Document how to mock repositories
  docs/testing.md
Labels: kind/documentation

#938 Add support for `azurerm_storage_account` and `azurerm_storage_container`
  .circleci/config.yml
  go.mod
  go.sum
  pkg/cmd/driftctl_test.go
  pkg/cmd/scan_test.go
  pkg/remote/azurerm/azurerm_storage_account_enumerator.go
  pkg/remote/azurerm/azurerm_storage_container_enumerator.go
  pkg/remote/azurerm/common/config.go
  pkg/remote/azurerm/init.go
  pkg/remote/azurerm/provider.go
  pkg/remote/azurerm/repository/mock_StorageRespository.go
  pkg/remote/azurerm/repository/mock_blobContainerClient.go
  pkg/remote/azurerm/repository/mock_storageAccountClient.go
  pkg/remote/azurerm/repository/storage.go
  pkg/remote/azurerm/repository/storage_test.go
  pkg/remote/azurerm_storage_scanner_test.go
  pkg/remote/common/providers.go
  pkg/remote/remote.go
  pkg/remote/terraform/provider.go
  pkg/resource/azurerm/azurerm_storage_account.go
  pkg/resource/azurerm/azurerm_storage_container.go
  pkg/resource/azurerm/azurerm_storage_container_test.go
  pkg/resource/azurerm/metadata.go
  pkg/resource/azurerm/testdata/acc/azurerm_storage_container/.terraform.lock.hcl
  pkg/resource/azurerm/testdata/acc/azurerm_storage_container/terraform.tf
  pkg/resource/resource_types.go
  pkg/terraform/providers.go
  test/azure/mock_ListContainerItemPager.go
  test/azure/mock_StorageAccountPager.go
  test/azure/storage.go
  test/schemas/azurerm/2.71.0/schema.json
  test/terraform/provider.go
Labels: kind/enhancement

#859 do not fail if one multiple from is incorrect
  pkg/cmd/scan.go
  pkg/iac/errors.go
  pkg/iac/supplier/IacChainSupplier.go
  pkg/iac/supplier/IacChainSupplier_test.go
  pkg/iac/supplier/supplier.go
  pkg/iac/supplier/supplier_test.go
  pkg/iac/terraform/state/alerts.go
  pkg/iac/terraform/state/enumerator/file.go
  pkg/iac/terraform/state/enumerator/s3.go
  pkg/iac/terraform/state/enumerator/state_enumerator.go
  pkg/iac/terraform/state/terraform_state_reader.go
  pkg/resource/chain_supplier.go
  pkg/resource/chain_supplier_test.go
Labels: kind/enhancement

#1025 Add google_compute_firewall
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/google_compute_firewall/results.golden.json
  pkg/iac/terraform/state/test/google_compute_firewall/terraform.tfstate
  pkg/remote/google/google_compute_firewall_enumerator.go
  pkg/remote/google/init.go
  pkg/remote/google/repository/asset.go
  pkg/remote/google_compute_scanner_test.go
  pkg/remote/test/google_compute_firewall/google_compute_firewall-projects_cloudskiff-dev-elie_global_firewalls_test-firewall-0-test-firewall-0-cloudskiff-dev-elie.res.golden.json
  pkg/remote/test/google_compute_firewall/google_compute_firewall-projects_cloudskiff-dev-elie_global_firewalls_test-firewall-1-test-firewall-1-cloudskiff-dev-elie.res.golden.json
  pkg/remote/test/google_compute_firewall/google_compute_firewall-projects_cloudskiff-dev-elie_global_firewalls_test-firewall-2-test-firewall-2-cloudskiff-dev-elie.res.golden.json
  pkg/remote/test/google_compute_firewall/results.golden.json
  pkg/remote/test/google_compute_firewall/terraform.tf
  pkg/resource/google/google_compute_firewall.go
  pkg/resource/google/google_compute_firewall_test.go
  pkg/resource/google/metadatas.go
  pkg/resource/google/testdata/acc/google_compute_firewall/.terraform.lock.hcl
  pkg/resource/google/testdata/acc/google_compute_firewall/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1069 Fix azure may hide some errors
  pkg/remote/azurerm/repository/storage.go
  pkg/remote/azurerm/repository/storage_test.go
Labels: kind/bug

#1070 Fix azure authentication
  pkg/remote/azurerm/common/config.go
  pkg/remote/azurerm/provider.go
Labels: kind/bug

#1023 Add docs about middlewares
  docs/middlewares.md
Labels: kind/documentation

#1072 Update testing example
  docs/testing.md
Labels: kind/documentation

#1067 Add google_compute_router
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/google_compute_router/results.golden.json
  pkg/iac/terraform/state/test/google_compute_router/terraform.tfstate
  pkg/remote/google/google_compute_firewall_enumerator.go
  pkg/remote/google/google_compute_router_enumerator.go
  pkg/remote/google/init.go
  pkg/remote/google/repository/asset.go
  pkg/remote/google/util.go
  pkg/remote/google_compute_scanner_test.go
  pkg/resource/google/google_compute_router.go
  pkg/resource/google/google_compute_router_test.go
  pkg/resource/google/metadatas.go
  pkg/resource/google/testdata/acc/google_compute_router/.terraform.lock.hcl
  pkg/resource/google/testdata/acc/google_compute_router/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1073 Add google_compute_instance
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/google_compute_instance/results.golden.json
  pkg/iac/terraform/state/test/google_compute_instance/terraform.tfstate
  pkg/remote/google/google_compute_instance_enumerator.go
  pkg/remote/google/init.go
  pkg/remote/google/repository/asset.go
  pkg/remote/google_compute_scanner_test.go
  pkg/resource/google/google_compute_instance.go
  pkg/resource/google/google_compute_instance_test.go
  pkg/resource/google/testdata/acc/google_compute_instance/.terraform.lock.hcl
  pkg/resource/google/testdata/acc/google_compute_instance/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1079 Remove skip subscription for azure
  .circleci/config.yml
Labels: kind/maintenance

#1080 Fix github acceptance test
  pkg/resource/github/testdata/acc/github_branch_protection/terraform.tf
Labels: kind/maintenance

#1024 Add google_compute_network resource
  pkg/remote/google/google_compute_network_enumerator.go
  pkg/remote/google/init.go
  pkg/remote/google/repository/asset.go
  pkg/remote/google_compute_scanner_test.go
  pkg/remote/test/google_compute_network/google_compute_network-projects_driftctl-qa-1_global_networks_driftctl-unittest-1-driftctl-unittest-1.res.golden.json
  pkg/remote/test/google_compute_network/google_compute_network-projects_driftctl-qa-1_global_networks_driftctl-unittest-2-driftctl-unittest-2.res.golden.json
  pkg/remote/test/google_compute_network/google_compute_network-projects_driftctl-qa-1_global_networks_driftctl-unittest-3-driftctl-unittest-3.res.golden.json
  pkg/remote/test/google_compute_network/results.golden.json
  pkg/resource/google/google_compute_network.go
  pkg/resource/google/google_compute_network_test.go
  pkg/resource/google/metadatas.go
  pkg/resource/google/testdata/acc/google_compute_network/.terraform.lock.hcl
  pkg/resource/google/testdata/acc/google_compute_network/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1011 Implement aws_rds_cluster_instance resource
  pkg/driftctl.go
  pkg/middlewares/aws_rds_cluster_instance_expander.go
  pkg/middlewares/aws_rds_cluster_instance_expander_test.go
  pkg/resource/aws/aws_rds_cluster_instance.go
  pkg/resource/resource_types.go
Labels: kind/enhancement
