Repository snyk/driftctl, pull requests merged in 2021-11, with the labels that each got.

#1181 add support for azurerm_private_dns_a_record & azurerm_private_dns_aa…
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/azurerm_private_dns_a_record/results.golden.json
  pkg/iac/terraform/state/test/azurerm_private_dns_a_record/terraform.tfstate
  pkg/iac/terraform/state/test/azurerm_private_dns_aaaa_record/results.golden.json
  pkg/iac/terraform/state/test/azurerm_private_dns_aaaa_record/terraform.tfstate
  pkg/remote/azurerm/azurerm_privatedns_a_record_enumerator.go
  pkg/remote/azurerm/azurerm_privatedns_aaaa_record_enumerator.go
  pkg/remote/azurerm/init.go
  pkg/remote/azurerm/repository/mock_PrivateDNSRepository.go
  pkg/remote/azurerm/repository/mock_privateDNSRecordSetListPager.go
  pkg/remote/azurerm/repository/mock_privateRecordSetClient.go
  pkg/remote/azurerm/repository/privatedns.go
  pkg/remote/azurerm/repository/privatedns_test.go
  pkg/remote/azurerm_privatedns_scanner_test.go
  pkg/remote/test/azurerm_private_dns_a_record_multiple/azurerm_private_dns_a_record-_subscriptions_7bfb2c5c-7308-46ed-8ae4-fffa356eb406_resourceGroups_martin-dev_providers_Microsoft.Network_privateDnsZones_thisisatestusingtf.com_A_othertest.res.golden.json
  pkg/remote/test/azurerm_private_dns_a_record_multiple/azurerm_private_dns_a_record-_subscriptions_7bfb2c5c-7308-46ed-8ae4-fffa356eb406_resourceGroups_martin-dev_providers_Microsoft.Network_privateDnsZones_thisisatestusingtf.com_A_test.res.golden.json
  pkg/remote/test/azurerm_private_dns_a_record_multiple/results.golden.json
  pkg/remote/test/azurerm_private_dns_aaaaa_record_multiple/azurerm_private_dns_aaaa_record-_subscriptions_7bfb2c5c-7308-46ed-8ae4-fffa356eb406_resourceGroups_martin-dev_providers_Microsoft.Network_privateDnsZones_thisisatestusingtf.com_AAAA_othertest.res.golden.json
  pkg/remote/test/azurerm_private_dns_aaaaa_record_multiple/azurerm_private_dns_aaaa_record-_subscriptions_7bfb2c5c-7308-46ed-8ae4-fffa356eb406_resourceGroups_martin-dev_providers_Microsoft.Network_privateDnsZones_thisisatestusingtf.com_AAAA_test.res.golden.json
  pkg/remote/test/azurerm_private_dns_aaaaa_record_multiple/results.golden.json
  pkg/remote/test/azurerm_private_dns_private_zone_multiple/azurerm_private_dns_zone-_subscriptions_7bfb2c5c-7308-46ed-8ae4-fffa356eb406_resourceGroups_martin-dev_providers_Microsoft.Network_privateDnsZones_testmartin.com.res.golden.json
  pkg/remote/test/azurerm_private_dns_private_zone_multiple/azurerm_private_dns_zone-_subscriptions_7bfb2c5c-7308-46ed-8ae4-fffa356eb406_resourceGroups_martin-dev_providers_Microsoft.Network_privateDnsZones_thisisatestusingtf.com.res.golden.json
  pkg/remote/test/azurerm_private_dns_private_zone_multiple/azurerm_private_dns_zone-_subscriptions_7bfb2c5c-7308-46ed-8ae4-fffa356eb406_resourceGroups_martin-dev_providers_Microsoft.Network_privateDnsZones_thisisatestusingtf2.com.res.golden.json
  pkg/remote/test/azurerm_private_dns_private_zone_multiple/results.golden.json
  pkg/resource/azurerm/azurerm_private_dns_a_record.go
  pkg/resource/azurerm/azurerm_private_dns_a_record_test.go
  pkg/resource/azurerm/azurerm_private_dns_aaaa_record.go
  pkg/resource/azurerm/azurerm_private_dns_aaaa_record_test.go
  pkg/resource/azurerm/metadata.go
  pkg/resource/azurerm/metadata_test.go
  pkg/resource/azurerm/testdata/acc/azurerm_private_dns_a_record/.driftignore
  pkg/resource/azurerm/testdata/acc/azurerm_private_dns_a_record/terraform.tf
  pkg/resource/azurerm/testdata/acc/azurerm_private_dns_aaaa_record/.driftignore
  pkg/resource/azurerm/testdata/acc/azurerm_private_dns_aaaa_record/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1198 Add google_cloudrun_service
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/google_cloudrun_service/results.golden.json
  pkg/iac/terraform/state/test/google_cloudrun_service/terraform.tfstate
  pkg/remote/google/google_cloudrun_service_enumerator.go
  pkg/remote/google/init.go
  pkg/remote/google/repository/asset.go
  pkg/remote/google/repository/mock_AssetRepository.go
  pkg/remote/google_cloudrun_scanner_test.go
  pkg/resource/google/google_cloudrun_service.go
  pkg/resource/google/google_cloudrun_service_test.go
  pkg/resource/google/metadata_test.go
  pkg/resource/google/testdata/acc/google_cloudrun_service/.driftignore
  pkg/resource/google/testdata/acc/google_cloudrun_service/.terraform.lock.hcl
  pkg/resource/google/testdata/acc/google_cloudrun_service/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1212 Display progress bar in stdout
  pkg/cmd/scan.go
  pkg/cmd/scan/output/output.go
  pkg/cmd/scan/output/output_test.go
Labels: kind/bug

#1216 Support passing in the Terraform API URL to support Terraform Enterprise installations.
  pkg/cmd/scan.go
  pkg/iac/terraform/state/backend/backend.go
  pkg/iac/terraform/state/backend/tfcloud_config_reader.go
  pkg/iac/terraform/state/backend/tfcloud_config_reader_test.go
  pkg/iac/terraform/state/backend/tfcloud_reader.go
  pkg/iac/terraform/state/backend/tfcloud_reader_test.go
Labels: kind/enhancement

#1219 Force azure provider registration to false.
  pkg/remote/azurerm/provider.go
Labels: kind/bug

#1235 Display out of sync drifts only in deep mode
  pkg/analyser/analysis.go
  pkg/analyser/analyzer.go
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/console_test.go
  pkg/cmd/scan/output/json_test.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output_without_deep.txt
Labels: kind/enhancement

#1236 Fix hacky way to serve fake TF provider schema in tests
  docs/new-remote-provider.md
  test/schemas/shemas.go
  test/terraform/fake_terraform_provider.go
  test/terraform/schemas_test.go
Labels: kind/maintenance

#1240 Disable checks that cannot make PRs green
  .circleci/config.yml
Labels: kind/maintenance

#1228 Fix private DNS resources attributes
  pkg/remote/azurerm/azurerm_private_dns_cname_record_enumerator.go
  pkg/remote/azurerm/azurerm_privatedns_a_record_enumerator.go
  pkg/remote/azurerm/azurerm_privatedns_aaaa_record_enumerator.go
  pkg/remote/azurerm/azurerm_privatedns_mx_record_enumerator.go
  pkg/remote/azurerm/azurerm_privatedns_ptr_record_enumerator.go
  pkg/remote/azurerm/azurerm_privatedns_srv_record_enumerator.go
Labels: kind/bug

#1243 Fix inconsistent test for RetryFor
  test/acceptance/testing_test.go
Labels: kind/maintenance

#1237 Make version check test more dynamic
  pkg/cmd/driftctl_test.go
  pkg/cmd/version_test.go
Labels: kind/maintenance

#1238 Add a global switch to disable third party
  build/build.go
  main.go
  pkg/cmd/driftctl.go
  pkg/cmd/driftctl_test.go
  pkg/cmd/scan.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
  test/build.go
  test/mocks/MockBuild.go
Labels: kind/maintenance

#1245 Fix acceptance cli arguments
  test/acceptance/testing.go
Labels: kind/maintenance
