Repository snyk/driftctl, pull requests merged in 2021-12, with the labels that each got.

#1221 Add azurerm_lb_rule resource
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/azurerm_lb_rule/results.golden.json
  pkg/iac/terraform/state/test/azurerm_lb_rule/terraform.tfstate
  pkg/remote/azurerm/azurerm_lb_rule_enumerator.go
  pkg/remote/azurerm/init.go
  pkg/remote/azurerm/repository/mock_NetworkRepository.go
  pkg/remote/azurerm/repository/mock_loadBalancerRulesClient.go
  pkg/remote/azurerm/repository/mock_loadBalancerRulesListAllPager.go
  pkg/remote/azurerm/repository/network.go
  pkg/remote/azurerm/repository/network_test.go
  pkg/remote/azurerm_network_scanner_test.go
  pkg/remote/test/azurerm_lb_rule_multiple/17c4e2b7f4cc466670ccbd8dd1d506289fd818c0.res.golden.json
  pkg/remote/test/azurerm_lb_rule_multiple/2f725aa2c71898229fcfa091837deaa387bee9d8.res.golden.json
  pkg/remote/test/azurerm_lb_rule_multiple/results.golden.json
  pkg/resource/azurerm/azurerm_lb_rule.go
  pkg/resource/azurerm/azurerm_lb_rule_test.go
  pkg/resource/azurerm/metadata.go
  pkg/resource/azurerm/metadata_test.go
  pkg/resource/azurerm/testdata/acc/azurerm_lb_rule/.driftignore
  pkg/resource/azurerm/testdata/acc/azurerm_lb_rule/.terraform.lock.hcl
  pkg/resource/azurerm/testdata/acc/azurerm_lb_rule/terraform.tf
  pkg/resource/resource_types.go
  test/terraform/fake_terraform_provider.go
Labels: kind/enhancement

#1254 feat: human readable tfc workspace names
  go.mod
  go.sum
  pkg/iac/terraform/state/backend/backend.go
  pkg/iac/terraform/state/backend/tfcloud_reader.go
  pkg/iac/terraform/state/backend/tfcloud_reader_test.go
  test/mocks/StateVersions.go
  test/mocks/Workspaces.go
  test/tfe/tfe.go
Labels: kind/enhancement

#1196 Create changelog generator script
  scripts/changelog.sh
Labels: kind/maintenance

#1266 chore: add licensing acknowledgments
  .goreleaser.yml
Labels: kind/maintenance

#1232 Implement GCS backend
  pkg/cmd/driftctl_test.go
  pkg/cmd/scan_test.go
  pkg/iac/supplier/supplier_test.go
  pkg/iac/terraform/state/backend/backend.go
  pkg/iac/terraform/state/backend/gs_reader.go
  pkg/iac/terraform/state/backend/gs_reader_test.go
  test/google/storage.go
Labels: kind/enhancement

#1282 Avoid triggering auth in GCS backend tests
  pkg/iac/terraform/state/backend/gs_reader_test.go
  pkg/iac/terraform/state/backend/testdata/gcp_application_default_credentials.json
Labels: kind/maintenance

#1283 Delete unused GoogleStorageBucketIAMBindingTransformer middleware
  pkg/middlewares/aws_nat_gateway_eip_assoc.go
  pkg/middlewares/google_storage_bucket_iam_binding_transformer.go
Labels: kind/maintenance

#1253 Avoid reading unmanaged resources
  pkg/analyser/analysis.go
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/remote/common/mock_DetailsFetcher.go
  pkg/remote/scanner.go
  pkg/remote/scanner_test.go
  pkg/resource/mock_RemoteSupplier.go
  pkg/resource/resource.go
  pkg/resource/supplier.go
Labels: kind/enhancement

#1290 Fix google_compute_network read attributes
  pkg/remote/google/google_compute_network_enumerator.go
  pkg/resource/google/google_compute_network.go
Labels: kind/bug

#1291 User large circleci executors
  .circleci/config.yml
Labels: kind/maintenance

#1293 Fix google_compute_subnetwork attributes
  pkg/remote/google/google_compute_subnetwork_enumerator.go
  pkg/resource/google/google_compute_subnetwork.go
Labels: kind/bug

#1292 Improve testing for the GCS backend
  pkg/iac/terraform/state/backend/gs_reader.go
  pkg/iac/terraform/state/backend/gs_reader_test.go
  pkg/iac/terraform/state/backend/testdata/gcp_application_default_credentials.json
Labels: kind/maintenance

#1294 Use docker executor for tests
  .circleci/config.yml
Labels: kind/maintenance

#1288 Add custom changelog to goreleaser command
  .gitignore
  scripts/build.sh
  scripts/changelog.sh
Labels: kind/maintenance

#1301 Revert "refactor: avoid reading unmanaged resources"
  pkg/analyser/analysis.go
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/remote/common/mock_DetailsFetcher.go
  pkg/remote/scanner.go
  pkg/remote/scanner_test.go
  pkg/resource/mock_RemoteSupplier.go
  pkg/resource/resource.go
  pkg/resource/supplier.go
Labels: kind/bug, priority/0

#1304 Fix acceptance test for google_bigquery_table
  pkg/resource/google/google_bigquery_table_test.go
Labels: kind/maintenance
