Repository snyk/driftctl, pull requests merged in 2021-08, with the labels that each got.

#901 Group changes by IaC source in console output
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/html_test.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output.txt
  pkg/cmd/scan/output/testdata/output_computed_fields.txt
  pkg/cmd/scan/output/testdata/output_json_fields.txt
  pkg/cmd/scan/output/testdata/output_stringer_resources.txt
  pkg/resource/resource.go
Labels: kind/enhancement

#908 Allow to customize read attributes in detail fetcher
  pkg/remote/common/details_fetcher.go
  pkg/resource/schemas.go
Labels: kind/maintenance, priority/0

#910 Add schema creation helper
  test/schemas/schemas_test.go
  test/schemas/shemas.go
  test/terraform/fake_terraform_provider.go
Labels: kind/maintenance

#895 Allow to build single binary in release mode
  Dockerfile
  Makefile
  scripts/build.sh
Labels: kind/maintenance

#924 Remove useless details fetchers
  pkg/remote/aws/dynamodb_table_details_fetcher.go
  pkg/remote/aws/ec2_default_route_table_details_fetcher.go
  pkg/remote/aws/ec2_route_details_fetcher.go
  pkg/remote/aws/ec2_route_table_association_details_fetcher.go
  pkg/remote/aws/iam_access_key_details_fetcher.go
  pkg/remote/aws/iam_role_policy_attachment_details_fetcher.go
  pkg/remote/aws/iam_user_policy_attachment_details_fetcher.go
  pkg/remote/aws/init.go
  pkg/remote/aws/lambda_function_details_fetcher.go
  pkg/remote/aws/s3_bucket_analytic_detail_fetcher.go
  pkg/remote/aws/s3_bucket_details_fetcher.go
  pkg/remote/aws/s3_bucket_inventory_details_fetcher.go
  pkg/remote/aws/s3_bucket_metrics_details_fetcher.go
  pkg/remote/aws/s3_bucket_notification_details_fetcher.go
  pkg/remote/aws/s3_bucket_policy_detail_fetcher.go
  pkg/remote/aws/sns_topic_details_fetcher.go
  pkg/remote/aws/sns_topic_policy_details_fetcher.go
  pkg/remote/aws/sns_topic_subscription_details_fetcher.go
  pkg/remote/aws/vpc_security_group_rule_details_fetcher.go
  pkg/remote/dynamodb_scanner_test.go
  pkg/remote/ec2_scanner_test.go
  pkg/remote/iam_scanner_test.go
  pkg/remote/lambda_scanner_test.go
  pkg/remote/s3_scanner_test.go
  pkg/remote/sns_scanner_test.go
  pkg/resource/aws/aws_default_route_table.go
  pkg/resource/aws/aws_dynamodb_table.go
  pkg/resource/aws/aws_iam_access_key.go
  pkg/resource/aws/aws_iam_role_policy_attachment.go
  pkg/resource/aws/aws_iam_user_policy_attachment.go
  pkg/resource/aws/aws_lambda_function.go
  pkg/resource/aws/aws_route.go
  pkg/resource/aws/aws_route_table_association.go
  pkg/resource/aws/aws_s3_bucket.go
  pkg/resource/aws/aws_s3_bucket_analytics_configuration.go
  pkg/resource/aws/aws_s3_bucket_inventory.go
  pkg/resource/aws/aws_s3_bucket_metric.go
  pkg/resource/aws/aws_s3_bucket_notification.go
  pkg/resource/aws/aws_s3_bucket_policy.go
  pkg/resource/aws/aws_security_group_rule.go
  pkg/resource/aws/aws_sns_topic.go
  pkg/resource/aws/aws_sns_topic_policy.go
  pkg/resource/aws/aws_sns_topic_subscription.go
  pkg/resource/aws/metadatas.go
Labels: kind/maintenance

#930 Embed images in HTML output
  pkg/cmd/scan/output/assets/driftctl_light.svg
  pkg/cmd/scan/output/assets/favicon.ico
  pkg/cmd/scan/output/assets/index.tmpl
  pkg/cmd/scan/output/assets/style.css
  pkg/cmd/scan/output/html.go
  pkg/cmd/scan/output/testdata/output.html
  pkg/cmd/scan/output/testdata/output_empty.html
  pkg/cmd/scan/output/testdata/output_sync.html
Labels: kind/enhancement

#932 Improve assertions on alerter mock in tests
  pkg/remote/cloudfront_scanner_test.go
  pkg/remote/dynamodb_scanner_test.go
  pkg/remote/ec2_scanner_test.go
  pkg/remote/ecr_scanner_test.go
  pkg/remote/github_branch_protection_scanner_test.go
  pkg/remote/github_membership_scanner_test.go
  pkg/remote/github_repository_scanner_test.go
  pkg/remote/github_team_membership_scanner_test.go
  pkg/remote/github_team_scanner_test.go
  pkg/remote/iam_scanner_test.go
  pkg/remote/kms_scanner_test.go
  pkg/remote/lambda_scanner_test.go
  pkg/remote/rds_scanner_test.go
  pkg/remote/route53_scanner_test.go
  pkg/remote/s3_scanner_test.go
  pkg/remote/sns_scanner_test.go
  pkg/remote/sqs_scanner_test.go
Labels: kind/maintenance

#927 Fix JSON diff formatting in HTML output
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/html.go
  pkg/cmd/scan/output/html_test.go
  pkg/cmd/scan/output/testdata/output.html
Labels: kind/bug, priority/1

#904 update documentation for contributors to be able to add new resources and remote
  docs/README.md
  docs/media/generalflow.png
  docs/media/generalflow.puml
  docs/media/resource.png
  docs/media/resource.puml
  docs/new-remote-provider.md
  docs/new-resource.md
  docs/testing.md
Labels: kind/documentation

#913 Add google_storage_bucket
  .circleci/config.yml
  go.mod
  go.sum
  pkg/cmd/driftctl_test.go
  pkg/cmd/scan_test.go
  pkg/remote/alerts/alerts.go
  pkg/remote/cache/mock_Cache.go
  pkg/remote/common/providers.go
  pkg/remote/google/config/config.go
  pkg/remote/google/google_storage_bucket_enumerator.go
  pkg/remote/google/init.go
  pkg/remote/google/provider.go
  pkg/remote/google/repository/asset.go
  pkg/remote/google/repository/asset_test.go
  pkg/remote/google_storage_scanner_test.go
  pkg/remote/remote.go
  pkg/remote/resource_enumeration_error_handler.go
  pkg/remote/resource_enumeration_error_handler_test.go
  pkg/remote/test/google_storage_bucket/google_storage_bucket-driftctl-unittest-1-driftctl-unittest-1.res.golden.json
  pkg/remote/test/google_storage_bucket/google_storage_bucket-driftctl-unittest-2-driftctl-unittest-2.res.golden.json
  pkg/remote/test/google_storage_bucket/google_storage_bucket-driftctl-unittest-3-driftctl-unittest-3.res.golden.json
  pkg/remote/test/google_storage_bucket/results.golden.json
  pkg/resource/google/google_storage_bucket.go
  pkg/resource/google/google_storage_bucket_test.go
  pkg/resource/google/metadatas.go
  pkg/resource/google/testdata/acc/google_storage_bucket/.terraform.lock.hcl
  pkg/resource/google/testdata/acc/google_storage_bucket/terraform.tf
  pkg/resource/resource_types.go
  pkg/terraform/providers.go
  test/google/asset.go
  test/schemas/google/3.78.0/schema.json
  test/terraform/provider.go
Labels: kind/enhancement

#885 Should read terraform config file
  pkg/iac/terraform/state/backend/tfcloud_config_reader.go
  pkg/iac/terraform/state/backend/tfcloud_config_reader_test.go
  pkg/iac/terraform/state/backend/tfcloud_reader.go
  pkg/iac/terraform/state/backend/tfcloud_reader_test.go
Labels: kind/enhancement
