Repository snyk/driftctl, pull requests merged in 2021-06, with the labels that each got.

#547 Implement caching in EC2 repository
  pkg/remote/aws/cloudfront_distribution_supplier.go
  pkg/remote/aws/cloudfront_distribution_supplier_test.go
  pkg/remote/aws/db_instance_supplier.go
  pkg/remote/aws/db_instance_supplier_test.go
  pkg/remote/aws/db_subnet_group_supplier.go
  pkg/remote/aws/db_subnet_group_supplier_test.go
  pkg/remote/aws/dynamodb_table_supplier.go
  pkg/remote/aws/dynamodb_table_supplier_test.go
  pkg/remote/aws/ec2_ami_supplier.go
  pkg/remote/aws/ec2_ami_supplier_test.go
  pkg/remote/aws/ec2_ebs_snapshot_supplier.go
  pkg/remote/aws/ec2_ebs_snapshot_supplier_test.go
  pkg/remote/aws/ec2_ebs_volume_supplier.go
  pkg/remote/aws/ec2_ebs_volume_supplier_test.go
  pkg/remote/aws/ec2_eip_association_supplier.go
  pkg/remote/aws/ec2_eip_association_supplier_test.go
  pkg/remote/aws/ec2_eip_supplier.go
  pkg/remote/aws/ec2_eip_supplier_test.go
  pkg/remote/aws/ec2_instance_supplier.go
  pkg/remote/aws/ec2_instance_supplier_test.go
  pkg/remote/aws/ec2_key_pair_supplier.go
  pkg/remote/aws/ec2_key_pair_supplier_test.go
  pkg/remote/aws/ecr_repository_supplier.go
  pkg/remote/aws/ecr_repository_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/kms_alias_supplier.go
  pkg/remote/aws/kms_alias_supplier_test.go
  pkg/remote/aws/kms_key_supplier.go
  pkg/remote/aws/kms_key_supplier_test.go
  pkg/remote/aws/lambda_event_source_mapping_supplier.go
  pkg/remote/aws/lambda_event_source_mapping_supplier_test.go
  pkg/remote/aws/lambda_function_supplier.go
  pkg/remote/aws/lambda_function_supplier_test.go
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
  pkg/remote/aws/route53_health_check_supplier.go
  pkg/remote/aws/route53_health_check_supplier_test.go
  pkg/remote/aws/route53_record_supplier.go
  pkg/remote/aws/route53_record_supplier_test.go
  pkg/remote/aws/route53_zone_supplier.go
  pkg/remote/aws/route53_zone_supplier_test.go
  pkg/remote/aws/sns_topic_policy_supplier.go
  pkg/remote/aws/sns_topic_policy_supplier_test.go
  pkg/remote/aws/sns_topic_subscription_supplier.go
  pkg/remote/aws/sns_topic_subscription_supplier_test.go
  pkg/remote/aws/sns_topic_supplier.go
  pkg/remote/aws/sns_topic_supplier_test.go
  pkg/remote/aws/sqs_queue_policy_supplier.go
  pkg/remote/aws/sqs_queue_policy_supplier_test.go
  pkg/remote/aws/sqs_queue_supplier.go
  pkg/remote/aws/sqs_queue_supplier_test.go
  pkg/remote/cache/cache.go
  pkg/remote/cache/cache_test.go
Labels: kind/enhancement

#591 Fix unsupported resources read from state files
  pkg/iac/terraform/state/terraform_state_reader.go
  pkg/resource/resource_types.go
Labels: kind/bug

#592 Improve testing for EC2 repository cache
  pkg/remote/aws/repository/ec2_repository.go
  pkg/remote/aws/repository/ec2_repository_test.go
Labels: kind/maintenance

#589 Fix crash when capacity is set to 0 in cache
  pkg/remote/cache/cache.go
  pkg/remote/cache/cache_test.go
Labels: kind/maintenance

#575 Fix error reporting in http state reader
  pkg/iac/terraform/state/terraform_state_reader.go
Labels: kind/bug

#577 Allow to specify a terraform provider version
  pkg/cmd/scan.go
  pkg/cmd/scan_test.go
  pkg/driftctl.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/init_test.go
  pkg/remote/aws/provider.go
  pkg/remote/github/init.go
  pkg/remote/github/init_test.go
  pkg/remote/github/provider.go
  pkg/remote/remote.go
  pkg/terraform/error/provider_download_error.go
  pkg/terraform/provider_config.go
  pkg/terraform/provider_config_test.go
  pkg/terraform/provider_downloader.go
  pkg/terraform/provider_downloader_test.go
  pkg/terraform/provider_installer.go
  pkg/terraform/provider_installer_test.go
Labels: kind/enhancement

#588 Implement cache in AWS SQS repository
  pkg/remote/aws/init.go
  pkg/remote/aws/repository/sqs_repository.go
  pkg/remote/aws/repository/sqs_repository_test.go
  pkg/remote/aws/sqs_queue_policy_supplier_test.go
  pkg/remote/aws/sqs_queue_supplier_test.go
Labels: kind/maintenance

#582 Implement cache in AWS RDS repository
  pkg/remote/aws/db_instance_supplier_test.go
  pkg/remote/aws/db_subnet_group_supplier_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/repository/rds_repository.go
  pkg/remote/aws/repository/rds_repository_test.go
Labels: kind/maintenance

#581 Implement cache in AWS lambda repository
  pkg/remote/aws/init.go
  pkg/remote/aws/lambda_event_source_mapping_supplier_test.go
  pkg/remote/aws/lambda_function_supplier_test.go
  pkg/remote/aws/repository/lambda_repository.go
  pkg/remote/aws/repository/lambda_repository_test.go
Labels: kind/maintenance

#585 Implement cache in Github repository
  pkg/remote/github/init.go
  pkg/remote/github/repository.go
  pkg/remote/github/repository_test.go
Labels: kind/maintenance

#579 Implement cache in AWS route53 repository
  pkg/remote/aws/init.go
  pkg/remote/aws/repository/route53_repository.go
  pkg/remote/aws/repository/route53_repository_test.go
  pkg/remote/aws/route53_health_check_supplier_test.go
  pkg/remote/aws/route53_record_supplier_test.go
  pkg/remote/aws/route53_zone_supplier_test.go
Labels: kind/maintenance

#595 Implement cache in AWS SNS repository
  pkg/remote/aws/init.go
  pkg/remote/aws/repository/sns_repository.go
  pkg/remote/aws/repository/sns_repository_test.go
  pkg/remote/aws/sns_topic_policy_supplier_test.go
  pkg/remote/aws/sns_topic_subscription_supplier_test.go
  pkg/remote/aws/sns_topic_supplier_test.go
  pkg/resource/aws/aws_sns_topic_policy_test.go
  pkg/resource/aws/aws_sns_topic_subscription_test.go
  pkg/resource/aws/aws_sns_topic_test.go
Labels: kind/maintenance

#578 Implement cache in AWS S3 repository
  pkg/remote/aws/init.go
  pkg/remote/aws/repository/s3_repository.go
  pkg/remote/aws/repository/s3_repository_test.go
  pkg/remote/aws/s3_bucket_analytic_supplier_test.go
  pkg/remote/aws/s3_bucket_inventory_supplier_test.go
  pkg/remote/aws/s3_bucket_metric_supplier_test.go
  pkg/remote/aws/s3_bucket_notification_supplier_test.go
  pkg/remote/aws/s3_bucket_policy_supplier_test.go
  pkg/remote/aws/s3_bucket_supplier_test.go
Labels: kind/maintenance

#607 Retrieve provider version and schema version
  pkg/remote/aws/init.go
  pkg/remote/aws/provider.go
  pkg/remote/github/init.go
  pkg/remote/github/provider.go
  pkg/resource/schemas.go
  test/resource/resource.go
Labels: kind/enhancement

#631 Enable diff on instance_initiated_shutdown_behavior field
  pkg/resource/aws/aws_instance.go
Labels: kind/bug

#645 Add terraform and providers version to bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: kind/maintenance

#650 Fix issue when enumerating s3 states on windows
  pkg/iac/terraform/state/enumerator/s3.go
Labels: kind/bug

#651 Fix state enumeration on s3 on win when using wildcards
  pkg/iac/terraform/state/enumerator/glob.go
  pkg/iac/terraform/state/enumerator/s3.go
Labels: kind/bug

#652 Allow to override OS_ARCH in build script
  scripts/build.sh
Labels: kind/maintenance

#657 Fix ses_smtp_password false positive
  pkg/resource/aws/aws_iam_access_key.go
Labels: kind/bug

#629 Add config-dir flag to change .driftctl location
  pkg/cmd/scan.go
  pkg/driftctl.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/init_test.go
  pkg/remote/aws/provider.go
  pkg/remote/github/init.go
  pkg/remote/github/init_test.go
  pkg/remote/github/provider.go
  pkg/remote/remote.go
  pkg/terraform/provider_config.go
  pkg/terraform/provider_installer.go
  pkg/terraform/provider_installer_test.go
Labels: kind/enhancement

#658 Display terraform provider version in output
  pkg/cmd/scan.go
  pkg/resource/schemas.go
Labels: kind/enhancement

#664 Fix EBS volume drift on throughput
  pkg/resource/aws/aws_ebs_volume.go
  pkg/resource/aws/aws_instance_test.go
  pkg/resource/aws/testdata/acc/aws_instance_default/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_instance_default/terraform.tf
Labels: kind/bug

#662 Fix aws_route carrier_gateway_id false positive
  pkg/resource/aws/aws_route.go
Labels: kind/bug

#661 aws sns topic/policy fix false positive
  pkg/resource/aws/aws_sns_topic.go
  pkg/resource/aws/aws_sns_topic_policy.go
Labels: kind/bug

#663 Handle managed_policy_arns in aws_iam_roles
  Makefile
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/middlewares/aws_defaults.go
  pkg/middlewares/aws_role_managed_policy_expander.go
  pkg/resource/aws/aws_iam_role_test.go
  pkg/resource/aws/testdata/acc/aws_iam_role/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_iam_role/terraform.tf
  pkg/resource/aws/testdata/acc/aws_iam_role_with_managed_policies/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_iam_role_with_managed_policies/terraform.tf
Labels: kind/bug

#674 Add missing attribute to volume expander middleware
  pkg/middlewares/aws_instance_block_device.go
  pkg/middlewares/aws_instance_block_device_test.go
Labels: kind/bug

#676 Fix dupplicate resource when expanding managed_policy fields
  pkg/driftctl_test.go
  pkg/middlewares/aws_role_managed_policy_expander.go
Labels: kind/bug

#678 Add limitation link in computed field alert
  pkg/analyser/analyzer.go
  pkg/cmd/scan/output/testdata/output_computed_fields.json
  pkg/cmd/scan/output/testdata/output_computed_fields.txt
Labels: kind/bug

#455 Implement HTML output
  pkg/analyser/analysis.go
  pkg/cmd/driftctl_test.go
  pkg/cmd/scan.go
  pkg/cmd/scan/output/assets/index.tmpl
  pkg/cmd/scan/output/assets/style.css
  pkg/cmd/scan/output/html.go
  pkg/cmd/scan/output/html_test.go
  pkg/cmd/scan/output/output.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output.html
  pkg/cmd/scan/output/testdata/output_empty.html
  pkg/cmd/scan/output/testdata/output_sync.html
  pkg/cmd/scan_test.go
  pkg/driftctl.go
Labels: kind/enhancement

#688 Fix golden files update
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/remote/aws/init_test.go
  pkg/terraform/provider_installer.go
Labels: kind/maintenance

#689 Add need-triage label to new issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: kind/maintenance

#619 Split suppliers to add deep mode
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/cmd/scan.go
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/remote/aws/init.go
  pkg/remote/aws/repository/mock_S3Repository.go
  pkg/remote/aws/repository/s3_repository.go
  pkg/remote/aws/repository/s3_repository_test.go
  pkg/remote/aws/s3_bucket_analytic_supplier.go
  pkg/remote/aws/s3_bucket_analytic_supplier_test.go
  pkg/remote/aws/s3_bucket_detail_fetcher.go
  pkg/remote/aws/s3_bucket_enumerator.go
  pkg/remote/aws/s3_bucket_inventory_supplier.go
  pkg/remote/aws/s3_bucket_inventory_supplier_test.go
  pkg/remote/aws/s3_bucket_metric_supplier_test.go
  pkg/remote/aws/s3_bucket_metrics_supplier.go
  pkg/remote/aws/s3_bucket_notification_supplier.go
  pkg/remote/aws/s3_bucket_notification_supplier_test.go
  pkg/remote/aws/s3_bucket_policy_supplier.go
  pkg/remote/aws/s3_bucket_policy_supplier_test.go
  pkg/remote/aws/s3_bucket_supplier.go
  pkg/remote/aws/s3_bucket_supplier_test.go
  pkg/remote/common/library.go
  pkg/remote/github/init.go
  pkg/remote/remote.go
  pkg/resource/deserializer.go
  pkg/scanner.go
Labels: kind/enhancement

#696 Fix S3 broken glob matching
  pkg/iac/terraform/state/enumerator/glob.go
  pkg/iac/terraform/state/enumerator/s3.go
  pkg/iac/terraform/state/enumerator/s3_test.go
Labels: kind/bug

#768 Add generic detail fetcher
  pkg/remote/common/detail_fetcher.go
  pkg/remote/common/library.go
Labels: kind/maintenance
