Repository snyk/driftctl, pull requests merged in 2021-03, with the labels that each got.

#304 Add github membership
  doc/cmd/scan/supported_resources/github.md
  pkg/iac/deserializers.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/github_membership/result.golden.json
  pkg/iac/terraform/state/test/github_membership/schema.golden.json
  pkg/iac/terraform/state/test/github_membership/terraform.tfstate
  pkg/remote/github/github_membership_supplier.go
  pkg/remote/github/github_membership_supplier_test.go
  pkg/remote/github/init.go
  pkg/remote/github/mock_GithubRepository.go
  pkg/remote/github/repository.go
  pkg/remote/github/repository_test.go
  pkg/remote/github/test/github_membership_empty/results.golden.json
  pkg/remote/github/test/github_membership_empty/schema.golden.json
  pkg/remote/github/test/github_membership_multiple/github_membership-driftctl-test_driftctl-acceptance-tester.res.golden.json
  pkg/remote/github/test/github_membership_multiple/github_membership-driftctl-test_eliecharra.res.golden.json
  pkg/remote/github/test/github_membership_multiple/results.golden.json
  pkg/remote/github/test/github_membership_multiple/schema.golden.json
  pkg/resource/github/deserializer/github_membership_deserializer.go
  pkg/resource/github/github_membership.go
Labels: kind/enhancement

#301 Add github_branch_protection
  doc/LIMITATIONS.md
  doc/cmd/scan/supported_resources/github.md
  pkg/iac/deserializers.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/github_branch_protection/result.golden.json
  pkg/iac/terraform/state/test/github_branch_protection/schema.golden.json
  pkg/iac/terraform/state/test/github_branch_protection/terraform.tfstate
  pkg/remote/github/github_branch_protection_supplier.go
  pkg/remote/github/github_branch_protection_supplier_test.go
  pkg/remote/github/init.go
  pkg/remote/github/mock_GithubRepository.go
  pkg/remote/github/provider.go
  pkg/remote/github/repository.go
  pkg/remote/github/repository_test.go
  pkg/remote/github/test/github_branch_protection_empty/results.golden.json
  pkg/remote/github/test/github_branch_protection_empty/schema.golden.json
  pkg/remote/github/test/github_branch_protection_multiples/github_branch_protection-MDIwOkJyYW5jaFByb3RlY3Rpb25SdWxlMTk1NDg0NzE=.res.golden.json
  pkg/remote/github/test/github_branch_protection_multiples/github_branch_protection-MDIwOkJyYW5jaFByb3RlY3Rpb25SdWxlMTk1NDg0NzI=.res.golden.json
  pkg/remote/github/test/github_branch_protection_multiples/github_branch_protection-MDIwOkJyYW5jaFByb3RlY3Rpb25SdWxlMTk1NDg0NzQ=.res.golden.json
  pkg/remote/github/test/github_branch_protection_multiples/github_branch_protection-MDIwOkJyYW5jaFByb3RlY3Rpb25SdWxlMTk1NDg0Nzc=.res.golden.json
  pkg/remote/github/test/github_branch_protection_multiples/github_branch_protection-MDIwOkJyYW5jaFByb3RlY3Rpb25SdWxlMTk1NDg0Nzg=.res.golden.json
  pkg/remote/github/test/github_branch_protection_multiples/github_branch_protection-MDIwOkJyYW5jaFByb3RlY3Rpb25SdWxlMTk1NDg0ODA=.res.golden.json
  pkg/remote/github/test/github_branch_protection_multiples/results.golden.json
  pkg/remote/github/test/github_branch_protection_multiples/schema.golden.json
  pkg/remote/github/test/github_branch_protection_multiples/terraform.tf
  pkg/resource/github/deserializer/github_branch_protection_deserializer.go
  pkg/resource/github/github_branch_protection.go
  pkg/resource/github/github_branch_protection_ext.go
  pkg/resource/github/github_branch_protection_ext_test.go
  pkg/resource/github/github_branch_protection_test.go
  pkg/resource/github/testdata/acc/github_branch_protection/.terraform.lock.hcl
  pkg/resource/github/testdata/acc/github_branch_protection/terraform.tf
Labels: kind/enhancement

#308 Handle enumeration error from github provider
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/console_test.go
  pkg/cmd/scan/output/json_test.go
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.txt
  pkg/cmd/scan/output/testdata/output_access_denied_alert_github.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert_github.txt
  pkg/remote/resource_enumeration_error_handler.go
  pkg/remote/resource_enumeration_error_handler_test.go
Labels: kind/enhancement

#303 Update documentation architecture
  .github/CONTRIBUTING.md
  README.md
  assets/icon.png
  assets/icon.svg
  assets/new_icon.svg
  doc/LIMITATIONS.md
  doc/README.md
  doc/cmd/completion/script.md
  doc/cmd/flags/error-reporting.md
  doc/cmd/flags/img/sentry.png
  doc/cmd/scan/filter.md
  doc/cmd/scan/iac_source.md
  doc/cmd/scan/output.md
  doc/cmd/scan/supported_resources/README.md
  doc/cmd/scan/supported_resources/aws.md
  doc/cmd/scan/supported_resources/github.md
  doc/contributing/README.md
  docs/README.md
  docs/media/resource.png
  docs/media/resource.puml
  docs/new-resource.md
  docs/testing.md
Labels: kind/documentation

#313 Fix bug on deserializing aws_iam_policy_attachment
  pkg/middlewares/iam_policy_attachment_sanitizer.go
  pkg/middlewares/iam_policy_attachment_sanitizer_test.go
  pkg/resource/aws/aws_iam_policy_attachment.go
  pkg/resource/aws/deserializer/iam_role_policy_attachment_deserializer.go
  pkg/resource/aws/deserializer/iam_user_policy_attachment_deserializer.go
Labels: kind/bug

#315 Add line number in log when invalid driftignore line encountered
  pkg/filter/driftignore.go
Labels: kind/enhancement

#328 Fix false positive in aws_db_subnet_group
  pkg/resource/aws/aws_db_subnet_group.go
Labels: kind/bug

#329 Fix false positive drift on aws_db_instance
  pkg/resource/aws/aws_db_instance.go
  pkg/resource/aws/aws_db_instance_ext.go
Labels: kind/bug

#330 Change error message to avoid unrelated error grouping on sentry
  pkg/driftctl.go
Labels: kind/maintenance

#310 refacto output print to prevent breaking output isolation
  .editorconfig
  Makefile
  goland_watchers.xml
  main.go
  pkg/cmd/scan.go
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/console_test.go
  pkg/cmd/scan/output/json.go
  pkg/cmd/scan/output/json_test.go
  pkg/cmd/scan/output/output.go
  pkg/cmd/scan/output/output_test.go
  pkg/output/printer.go
  pkg/remote/aws/provider.go
  pkg/remote/terraform/provider.go
  pkg/terraform/provider_installer.go
Labels: kind/enhancement

#333 Remove docker layer badge
  README.md
Labels: kind/maintenance

#336 add date to resources names for dynamo and lambda event source mapping acceptance tests
  pkg/resource/aws/testdata/acc/aws_dynamodb_table/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_dynamodb_table/main.tf
  pkg/resource/aws/testdata/acc/aws_lambda_event_source_mapping/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_lambda_event_source_mapping/main.tf
Labels: kind/maintenance

#339 fix race condition on progress that could cause deadlock
  pkg/output/progress.go
  pkg/output/progress_test.go
Labels: kind/bug, priority/0

#342 Asking for users feedback on README
  README.md
Labels: kind/documentation

#344 Remove provider initialization message
  pkg/remote/terraform/provider.go
Labels: kind/maintenance, priority/3

#346 Fix race conditions when using multiples runners in a single supplier
  pkg/remote/aws/cloudfront_distribution_supplier.go
  pkg/remote/aws/db_instance_supplier.go
  pkg/remote/aws/db_subnet_group_supplier.go
  pkg/remote/aws/dynamodb_table_supplier.go
  pkg/remote/aws/ec2_ami_supplier.go
  pkg/remote/aws/ec2_ebs_snapshot_supplier.go
  pkg/remote/aws/ec2_ebs_volume_supplier.go
  pkg/remote/aws/ec2_eip_association_supplier.go
  pkg/remote/aws/ec2_eip_supplier.go
  pkg/remote/aws/ec2_instance_supplier.go
  pkg/remote/aws/ec2_key_pair_supplier.go
  pkg/remote/aws/ecr_repository_supplier.go
  pkg/remote/aws/iam_access_key_supplier.go
  pkg/remote/aws/iam_policy_supplier.go
  pkg/remote/aws/iam_role_policy_attachment_supplier.go
  pkg/remote/aws/iam_role_policy_supplier.go
  pkg/remote/aws/iam_role_supplier.go
  pkg/remote/aws/iam_user_policy_attachment_supplier.go
  pkg/remote/aws/iam_user_policy_supplier.go
  pkg/remote/aws/iam_user_supplier.go
  pkg/remote/aws/internet_gateway_supplier.go
  pkg/remote/aws/kms_alias_supplier.go
  pkg/remote/aws/kms_key_supplier.go
  pkg/remote/aws/lambda_event_source_mapping_supplier.go
  pkg/remote/aws/lambda_function_supplier.go
  pkg/remote/aws/nat_gateway_supplier.go
  pkg/remote/aws/route53_health_check_supplier.go
  pkg/remote/aws/route53_record_supplier.go
  pkg/remote/aws/route53_zone_supplier.go
  pkg/remote/aws/route_supplier.go
  pkg/remote/aws/route_table_association_supplier.go
  pkg/remote/aws/route_table_supplier.go
  pkg/remote/aws/s3_bucket_supplier.go
  pkg/remote/aws/sns_topic_policy_supplier.go
  pkg/remote/aws/sns_topic_subscription_supplier.go
  pkg/remote/aws/sns_topic_supplier.go
  pkg/remote/aws/sqs_queue_policy_supplier.go
  pkg/remote/aws/sqs_queue_supplier.go
  pkg/remote/aws/subnet_supplier.go
  pkg/remote/aws/vpc_security_group_rule_supplier.go
  pkg/remote/aws/vpc_security_group_supplier.go
  pkg/remote/aws/vpc_supplier.go
Labels: kind/bug

#351 Fix missing mock on golden file update
  pkg/remote/aws/init_test.go
Labels: kind/bug

#335 Implement http(s) backend
  pkg/cmd/driftctl_test.go
  pkg/cmd/scan.go
  pkg/cmd/scan_test.go
  pkg/iac/supplier/supplier.go
  pkg/iac/supplier/supplier_test.go
  pkg/iac/terraform/state/backend/backend.go
  pkg/iac/terraform/state/backend/http_reader.go
  pkg/iac/terraform/state/backend/http_reader_test.go
  pkg/iac/terraform/state/backend/mock_ReaderMock.go
  pkg/iac/terraform/state/terraform_state_reader.go
Labels: kind/enhancement, priority/3

#348 Filter out s3 buckets from different regions
  pkg/remote/aws/s3_bucket_analytic_supplier.go
  pkg/remote/aws/s3_bucket_analytic_supplier_test.go
  pkg/remote/aws/s3_bucket_inventory_supplier.go
  pkg/remote/aws/s3_bucket_inventory_supplier_test.go
  pkg/remote/aws/s3_bucket_metric_supplier_test.go
  pkg/remote/aws/s3_bucket_metrics_supplier.go
  pkg/remote/aws/s3_bucket_notification_supplier.go
  pkg/remote/aws/s3_bucket_notification_supplier_test.go
  pkg/remote/aws/s3_bucket_policy_supplier.go
  pkg/remote/aws/s3_bucket_policy_supplier_test.go
  pkg/remote/aws/s3_bucket_supplier.go
  pkg/remote/aws/s3_bucket_supplier_test.go
  pkg/remote/aws/test/s3_bucket_analytics_multiple/aws_s3_bucket_analytics_configuration-bucket-martin-test-drift3_Analytics2_Bucket3.res.golden.json
  pkg/remote/aws/test/s3_bucket_analytics_multiple/aws_s3_bucket_analytics_configuration-bucket-martin-test-drift3_Analytics_Bucket3.res.golden.json
  pkg/remote/aws/test/s3_bucket_analytics_multiple/aws_s3_bucket_analytics_configuration-bucket-martin-test-drift_Analytics2_Bucket.res.golden.json
  pkg/remote/aws/test/s3_bucket_analytics_multiple/aws_s3_bucket_analytics_configuration-bucket-martin-test-drift_Analytics2_Bucket1.res.golden.json
  pkg/remote/aws/test/s3_bucket_analytics_multiple/aws_s3_bucket_analytics_configuration-bucket-martin-test-drift_Analytics_Bucket.res.golden.json
  pkg/remote/aws/test/s3_bucket_analytics_multiple/aws_s3_bucket_analytics_configuration-bucket-martin-test-drift_Analytics_Bucket1.res.golden.json
  pkg/remote/aws/test/s3_bucket_analytics_multiple/results.golden.json
  pkg/remote/aws/test/s3_bucket_inventories_multiple/aws_s3_bucket_inventory-bucket-martin-test-drift3_Inventory2_Bucket3.res.golden.json
  pkg/remote/aws/test/s3_bucket_inventories_multiple/aws_s3_bucket_inventory-bucket-martin-test-drift3_Inventory_Bucket3.res.golden.json
  pkg/remote/aws/test/s3_bucket_inventories_multiple/aws_s3_bucket_inventory-bucket-martin-test-drift_Inventory2_Bucket1.res.golden.json
  pkg/remote/aws/test/s3_bucket_inventories_multiple/aws_s3_bucket_inventory-bucket-martin-test-drift_Inventory_Bucket1.res.golden.json
  pkg/remote/aws/test/s3_bucket_inventories_multiple/results.golden.json
  pkg/remote/aws/test/s3_bucket_metrics_multiple/aws_s3_bucket_metric-bucket-martin-test-drift3_Metric2_Bucket3.res.golden.json
  pkg/remote/aws/test/s3_bucket_metrics_multiple/aws_s3_bucket_metric-bucket-martin-test-drift3_Metric_Bucket3.res.golden.json
  pkg/remote/aws/test/s3_bucket_metrics_multiple/aws_s3_bucket_metric-bucket-martin-test-drift3_Metrics2_Bucket3.res.golden.json
  pkg/remote/aws/test/s3_bucket_metrics_multiple/aws_s3_bucket_metric-bucket-martin-test-drift3_Metrics_Bucket3.res.golden.json
  pkg/remote/aws/test/s3_bucket_metrics_multiple/aws_s3_bucket_metric-bucket-martin-test-drift_Metric2_Bucket1.res.golden.json
  pkg/remote/aws/test/s3_bucket_metrics_multiple/aws_s3_bucket_metric-bucket-martin-test-drift_Metric_Bucket1.res.golden.json
  pkg/remote/aws/test/s3_bucket_metrics_multiple/aws_s3_bucket_metric-bucket-martin-test-drift_Metrics2_Bucket1.res.golden.json
  pkg/remote/aws/test/s3_bucket_metrics_multiple/aws_s3_bucket_metric-bucket-martin-test-drift_Metrics_Bucket1.res.golden.json
  pkg/remote/aws/test/s3_bucket_metrics_multiple/results.golden.json
  pkg/remote/aws/test/s3_bucket_multiple/aws_s3_bucket-bucket-martin-test-drift.res.golden.json
  pkg/remote/aws/test/s3_bucket_multiple/aws_s3_bucket-bucket-martin-test-drift3.res.golden.json
  pkg/remote/aws/test/s3_bucket_multiple/results.golden.json
  pkg/remote/aws/test/s3_bucket_notifications_multiple/aws_s3_bucket_notification-bucket-martin-test-drift.res.golden.json
  pkg/remote/aws/test/s3_bucket_notifications_multiple/aws_s3_bucket_notification-bucket-martin-test-drift3.res.golden.json
  pkg/remote/aws/test/s3_bucket_notifications_multiple/results.golden.json
  pkg/remote/aws/test/s3_bucket_policies_multiple/aws_s3_bucket_policy-bucket-martin-test-drift.res.golden.json
  pkg/remote/aws/test/s3_bucket_policies_multiple/aws_s3_bucket_policy-bucket-martin-test-drift3.res.golden.json
  pkg/remote/aws/test/s3_bucket_policies_multiple/results.golden.json
Labels: bug/confirmed, priority/1

#314 DriftIgnore implement new wildcard match checker
  pkg/filter/driftignore.go
  pkg/filter/driftignore_test.go
  pkg/filter/testdata/drift_ignore_wildcard/.driftignore
Labels: kind/enhancement

#356 Sort unmanaged & deleted resources in a predictable order
  pkg/analyser/analysis.go
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/resource/resource.go
Labels: kind/enhancement, priority/3

#364 remove dynamodb table replica to speed up acc tests
  pkg/resource/aws/testdata/acc/aws_dynamodb_table/main.tf
Labels: kind/maintenance

#380 Fix broken link in unmanaged security groups
  pkg/analyser/analyzer.go
Labels: kind/bug, next-version/patch

#383 Remove LastModified field for aws_lambda_function from drift reports
  pkg/resource/aws/aws_lambda_function.go
Labels: kind/bug, next-version/patch

#381 Add details to error reporting flag in help message
  pkg/cmd/driftctl.go
Labels: kind/documentation, next-version/patch

#379 Update output terminology
  pkg/analyser/analysis.go
  pkg/analyser/testdata/input.json
  pkg/analyser/testdata/output.json
  pkg/cmd/scan/output/console.go
  pkg/cmd/scan/output/testdata/output.json
  pkg/cmd/scan/output/testdata/output.txt
  pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert_github.json
  pkg/cmd/scan/output/testdata/output_computed_fields.json
  pkg/cmd/scan/output/testdata/output_computed_fields.txt
  pkg/cmd/scan/output/testdata/output_json_fields.txt
  pkg/cmd/scan/output/testdata/output_stringer_resources.txt
Labels: kind/enhancement, next-version/patch

#393 Add missing 'make deps' steps in CI
  .circleci/config.yml
Labels: kind/maintenance

#395 Allow to set args in checks in acceptance test
  test/acceptance/testing.go
Labels: kind/maintenance

#386 display last number of resources scanned and hide animation character when progress bar end
  pkg/output/progress.go
Labels: kind/bug, next-version/patch

#385 Make differences output predictable
  pkg/analyser/analysis.go
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
Labels: kind/bug, next-version/patch

#398 Fix false positive report on FinalSnapshotIdentifier field
  pkg/resource/aws/aws_db_instance.go
Labels: kind/bug, next-version/patch

#394 Fix json output
  pkg/cmd/scan/output/json.go
  pkg/cmd/scan/output/json_test.go
  pkg/cmd/scan/output/testdata/output_multiples_times.json
Labels: kind/bug, next-version/patch

#400 Prevent go test to update go.mod
  Makefile
Labels: kind/maintenance

#399 Add tests for driftctl
  pkg/driftctl.go
  pkg/driftctl_test.go
  pkg/iac/terraform/state/terraform_state_reader_acc_test.go
  pkg/resource/aws/aws_cloudfront_distribution_test.go
  pkg/resource/aws/aws_dynamodb_table_test.go
  pkg/resource/aws/aws_ecr_repository_test.go
  pkg/resource/aws/aws_instance_test.go
  pkg/resource/aws/aws_internet_gateway_test.go
  pkg/resource/aws/aws_kms_alias_test.go
  pkg/resource/aws/aws_kms_key_test.go
  pkg/resource/aws/aws_lambda_event_source_mapping_test.go
  pkg/resource/aws/aws_nat_gateway_test.go
  pkg/resource/aws/aws_route53_health_check_test.go
  pkg/resource/aws/aws_route53_record_test.go
  pkg/resource/aws/aws_route_table_association_test.go
  pkg/resource/aws/aws_route_table_test.go
  pkg/resource/aws/aws_route_test.go
  pkg/resource/aws/aws_s3_bucket_test.go
  pkg/resource/aws/aws_security_group_test.go
  pkg/resource/aws/aws_sns_topic_policy_test.go
  pkg/resource/aws/aws_sns_topic_subscription_test.go
  pkg/resource/aws/aws_sns_topic_test.go
  pkg/resource/aws/aws_sqs_queue_policy_test.go
  pkg/resource/aws/aws_sqs_queue_test.go
  pkg/resource/aws/aws_subnet_test.go
  pkg/resource/github/github_branch_protection_test.go
  pkg/resource/github/github_repository_test.go
  pkg/resource/github/github_team_membership_test.go
  pkg/resource/github/github_team_test.go
  pkg/resource/mock_Supplier.go
  test/acceptance/testing.go
  test/result.go
Labels: kind/maintenance
