Repository snyk/driftctl, pull requests merged in 2022-05, with the labels that each got.

#1479 Fix go-helper vulns + go mod tidy
  go.mod
  go.sum
Labels: kind/maintenance

#1478 Add client to telemetry
  main.go
  pkg/config/config.go
  pkg/telemetry/telemetry.go
  pkg/telemetry/telemetry_test.go
Labels: kind/maintenance

#1496 fix: weakness in eip enumerator
  pkg/remote/aws/ec2_eip_enumerator.go
  pkg/remote/aws_ec2_scanner_test.go
Labels: kind/bug

#1495 Add retry policy for google_compute_firewall acc test
  pkg/resource/google/google_compute_firewall_test.go
Labels: kind/maintenance

#1502 fix: crash in deep mode on aws_route
  pkg/resource/aws/aws_route.go
  pkg/resource/aws/aws_route_test.go
  pkg/resource/aws/testdata/acc/aws_route_with_prefix_list_id/.driftignore
  pkg/resource/aws/testdata/acc/aws_route_with_prefix_list_id/.terraform.lock.hcl
  pkg/resource/aws/testdata/acc/aws_route_with_prefix_list_id/terraform.tf
Labels: kind/bug, priority/1

#1501 fix: driftignore that ignore type
  pkg/filter/driftignore.go
  pkg/filter/driftignore_test.go
Labels: kind/bug
