Repository snyk/driftctl, pull requests merged in 2022-02, with the labels that each got.

#1345 Update retry policy for GCP acc tests
  pkg/resource/google/google_bigquery_table_test.go
  pkg/resource/google/google_compute_global_address_test.go
  test/acceptance/testing.go
Labels: kind/maintenance

#1347 Add retry policy for remaining GCP acc tests
  pkg/resource/google/google_bigquery_dataset_test.go
  pkg/resource/google/google_bigquery_table_test.go
  pkg/resource/google/google_bigtable_instance_test.go
  pkg/resource/google/google_bigtable_table_test.go
  pkg/resource/google/google_cloudfunctions_function_test.go
  pkg/resource/google/google_compute_global_address_test.go
  pkg/resource/google/google_compute_instance_test.go
  pkg/resource/google/google_compute_network_test.go
  pkg/resource/google/google_sql_database_instance_test.go
  pkg/resource/google/google_storage_bucket_test.go
  test/acceptance/testing.go
Labels: kind/maintenance

#1327 Add issue-tagging script
  .circleci/config.yml
  scripts/issue-tagging.sh
Labels: kind/maintenance

#1357 Add azure blob storage backend
  .circleci/config.yml
  go.mod
  go.sum
  pkg/analyser/analysis.go
  pkg/cmd/driftctl_test.go
  pkg/cmd/scan.go
  pkg/cmd/scan_test.go
  pkg/helpers/azure/storage.go
  pkg/iac/supplier/supplier_test.go
  pkg/iac/terraform/state/backend/azureblob_reader.go
  pkg/iac/terraform/state/backend/azureblob_reader_test.go
  pkg/iac/terraform/state/backend/backend.go
  pkg/iac/terraform/state/backend/options/azure.go
  pkg/iac/terraform/state/enumerator/azurerm.go
  pkg/iac/terraform/state/enumerator/state_enumerator.go
  pkg/iac/terraform/state/terraform_state_reader.go
  pkg/iac/terraform/state/terraform_state_reader_azure_acc_test.go
  pkg/iac/terraform/state/testdata/acc/multiples_states_azure/another_container_registry/.terraform.lock.hcl
  pkg/iac/terraform/state/testdata/acc/multiples_states_azure/another_container_registry/terraform.tf
  pkg/iac/terraform/state/testdata/acc/multiples_states_azure/container_registry/.terraform.lock.hcl
  pkg/iac/terraform/state/testdata/acc/multiples_states_azure/container_registry/terraform.tf
  test/acceptance/testing.go
Labels: kind/enhancement

#1360 Use voidprinter when sending HTML output to stdout
  pkg/cmd/scan/output/output.go
  pkg/cmd/scan/output/output_test.go
Labels: kind/bug
