Repository snyk/driftctl, pull requests merged in 2022-03, with the labels that each got.

#1362 Fix issue tagging script
  scripts/issue-tagging.sh
Labels: kind/maintenance

#1371 Add total_iac_source_count json field
  pkg/analyser/analysis.go
  pkg/analyser/analyzer_test.go
  pkg/analyser/testdata/input.json
  pkg/analyser/testdata/output.json
  pkg/cmd/scan/output/output_test.go
  pkg/cmd/scan/output/testdata/output.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert_github.json
  pkg/cmd/scan/output/testdata/output_computed_fields.json
  pkg/cmd/scan/output/testdata/output_multiples_times.json
  pkg/driftctl.go
  pkg/driftctl_test.go
Labels: kind/enhancement

#1372 Add `driftctl fmt` command
  pkg/analyser/analysis.go
  pkg/analyser/analyzer.go
  pkg/analyser/analyzer_test.go
  pkg/analyser/testdata/input.json
  pkg/analyser/testdata/output.json
  pkg/cmd/driftctl.go
  pkg/cmd/flags.go
  pkg/cmd/flags_test.go
  pkg/cmd/fmt.go
  pkg/cmd/fmt_test.go
  pkg/cmd/scan.go
  pkg/cmd/scan/output/testdata/output.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert_aws.json
  pkg/cmd/scan/output/testdata/output_access_denied_alert_github.json
  pkg/cmd/scan/output/testdata/output_computed_fields.json
  pkg/cmd/scan/output/testdata/output_multiples_times.json
  pkg/cmd/scan_test.go
  pkg/cmd/testdata/fmt/expected_console.txt
  pkg/cmd/testdata/fmt/input_stdin_invalid.json
  pkg/cmd/testdata/fmt/input_stdin_valid.json
  pkg/driftctl.go
Labels: kind/enhancement

#1377 Improve snyk piping
  main.go
  pkg/cmd/scan/output/output.go
  pkg/cmd/scan/output/output_test.go
  pkg/output/printer.go
Labels: kind/enhancement

#1380 Fix panic in apigatewayv2_api_mapping enumerator
  pkg/remote/aws/apigatewayv2_mapping_enumerator.go
  pkg/remote/aws_apigatewayv2_scanner_test.go
  pkg/resource/aws/aws_apigatewayv2_mapping.go
Labels: kind/bug

#1368 Add div block for brand logo in HTML output
  pkg/cmd/scan/output/assets/driftctl_light.svg
  pkg/cmd/scan/output/assets/index.tmpl
  pkg/cmd/scan/output/assets/style.css
  pkg/cmd/scan/output/testdata/output.html
  pkg/cmd/scan/output/testdata/output_coverage_100.html
  pkg/cmd/scan/output/testdata/output_empty.html
  pkg/cmd/scan/output/testdata/output_sync.html
Labels: kind/enhancement

#1445 [CFG-1601] Add blobs config to goreleaser file
  .goreleaser.yml
Labels: kind/maintenance

#1446 Fix issue parsing in issue tagging script
  scripts/issue-tagging.sh
Labels: kind/maintenance

#1379 Add google_compute_instance_group_manager
  pkg/driftctl.go
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/google_compute_instance_group_manager/results.golden.json
  pkg/iac/terraform/state/test/google_compute_instance_group_manager/terraform.tfstate
  pkg/middlewares/google_compute_instance_group_manager_reconciler.go
  pkg/middlewares/google_compute_instance_group_manager_reconciler_test.go
  pkg/remote/google/google_compute_instance_group_manager_enumerator.go
  pkg/remote/google/init.go
  pkg/remote/google/repository/asset.go
  pkg/remote/google/repository/mock_AssetRepository.go
  pkg/remote/google_compute_scanner_test.go
  pkg/resource/google/google_compute_instance_group_manager.go
  pkg/resource/google/google_compute_instance_group_manager_test.go
  pkg/resource/google/metadata_test.go
  pkg/resource/google/metadatas.go
  pkg/resource/google/testdata/acc/google_compute_instance_group_manager/.driftignore
  pkg/resource/google/testdata/acc/google_compute_instance_group_manager/.terraform.lock.hcl
  pkg/resource/google/testdata/acc/google_compute_instance_group_manager/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement

#1449 Remove hint from the diagnostic output
  pkg/cmd/scan.go
Labels: kind/enhancement

#1452 Disable usage reporting for non release builds
  build/build.go
Labels: kind/maintenance

#1453 feat: google compute global forwarding rule
  pkg/iac/terraform/state/terraform_state_reader_test.go
  pkg/iac/terraform/state/test/google_compute_global_forwarding_rule/results.golden.json
  pkg/iac/terraform/state/test/google_compute_global_forwarding_rule/terraform.tfstate
  pkg/remote/google/google_compute_global_forwarding_rule_enumerator.go
  pkg/remote/google/init.go
  pkg/remote/google/repository/asset.go
  pkg/remote/google/repository/mock_AssetRepository.go
  pkg/remote/google_compute_scanner_test.go
  pkg/resource/google/google_compute_global_forwarding_rule.go
  pkg/resource/google/google_compute_global_forwarding_rule_test.go
  pkg/resource/google/metadata_test.go
  pkg/resource/google/testdata/acc/google_compute_global_forwarding_rule/.driftignore
  pkg/resource/google/testdata/acc/google_compute_global_forwarding_rule/.terraform.lock.hcl
  pkg/resource/google/testdata/acc/google_compute_global_forwarding_rule/terraform.tf
  pkg/resource/resource_types.go
Labels: kind/enhancement
